// GENERATED by scripts/gen-prelude.ts — DO NOT EDIT.
// Regenerate with `bun run gen:prelude`. Guarded by test/prelude-shim.spec.ts.
// The standalone prelude-table shim for the self-hosted compiler (ticket 0004).
const _builtins = {
  "add": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "sub": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "mul": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "div": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "square": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "sqrt": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "hypot": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "pi": {
    "_tag": "TyCon",
    "name": "number",
    "args": []
  },
  "eq": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyVar",
      "id": 0
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "compare": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyVar",
      "id": 0
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "show": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyVar",
      "id": 0
    },
    "to": {
      "_tag": "TyCon",
      "name": "string",
      "args": []
    }
  },
  "lt": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "gt": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "gte": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "lte": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "not": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "bool",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "bool",
      "args": []
    }
  },
  "and": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "bool",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "or": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "bool",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "min": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "max": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "pow": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "mod": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    }
  },
  "abs": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "floor": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "ceil": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "round": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "sign": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "negate": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "length": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "Array",
      "args": [
        {
          "_tag": "TyVar",
          "id": 0
        }
      ]
    },
    "to": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    }
  },
  "map": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyVar",
        "id": 1
      }
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 1
          }
        ]
      }
    }
  },
  "filter": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    }
  },
  "reduce": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 1
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      }
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 1
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      }
    }
  },
  "identity": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyVar",
      "id": 0
    },
    "to": {
      "_tag": "TyVar",
      "id": 0
    }
  },
  "always": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyVar",
      "id": 0
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 1
      },
      "to": {
        "_tag": "TyVar",
        "id": 0
      }
    }
  },
  "compose": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 1
      },
      "to": {
        "_tag": "TyVar",
        "id": 2
      }
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 2
        }
      }
    }
  },
  "capitalize": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "string",
      "args": []
    },
    "to": {
      "_tag": "TyCon",
      "name": "string",
      "args": []
    }
  },
  "range": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyCon",
            "name": "number",
            "args": []
          }
        ]
      }
    }
  },
  "iterate": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyVar",
        "id": 0
      }
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    }
  },
  "repeat": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyVar",
      "id": 0
    },
    "to": {
      "_tag": "TyCon",
      "name": "List",
      "args": [
        {
          "_tag": "TyVar",
          "id": 0
        }
      ]
    }
  },
  "take": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    }
  },
  "takeWhile": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    }
  },
  "drop": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "number",
      "args": []
    },
    "to": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    }
  },
  "fromArray": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "Array",
      "args": [
        {
          "_tag": "TyVar",
          "id": 0
        }
      ]
    },
    "to": {
      "_tag": "TyCon",
      "name": "List",
      "args": [
        {
          "_tag": "TyVar",
          "id": 0
        }
      ]
    }
  },
  "toArray": {
    "_tag": "TyFn",
    "from": {
      "_tag": "TyCon",
      "name": "List",
      "args": [
        {
          "_tag": "TyVar",
          "id": 0
        }
      ]
    },
    "to": {
      "_tag": "TyCon",
      "name": "Array",
      "args": [
        {
          "_tag": "TyVar",
          "id": 0
        }
      ]
    }
  }
};
const _namespaces = {
  "Array": {
    "map": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "filter": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "reduce": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 1
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyVar",
            "id": 0
          },
          "to": {
            "_tag": "TyVar",
            "id": 1
          }
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 1
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyCon",
            "name": "Array",
            "args": [
              {
                "_tag": "TyVar",
                "id": 0
              }
            ]
          },
          "to": {
            "_tag": "TyVar",
            "id": 1
          }
        }
      }
    },
    "length": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    },
    "head": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "get": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "find": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "reverse": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "concat": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "append": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "prepend": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "flatMap": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "take": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "drop": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "tail": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "contains": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "sort": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "sortBy": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "dedupe": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "dedupeBy": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "max": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "min": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "maxBy": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "minBy": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    }
  },
  "List": {
    "map": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "filter": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "concat": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "flatMap": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "List",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "head": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "List",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    }
  },
  "Set": {
    "has": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "add": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "delete": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "size": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Set",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    },
    "toArray": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Set",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "fromArray": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Set",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "union": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Set",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "intersect": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Set",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "diff": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Set",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Set",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    }
  },
  "Map": {
    "has": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Map",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "getOr": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 1
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyCon",
            "name": "Map",
            "args": [
              {
                "_tag": "TyVar",
                "id": 0
              },
              {
                "_tag": "TyVar",
                "id": 1
              }
            ]
          },
          "to": {
            "_tag": "TyVar",
            "id": 1
          }
        }
      }
    },
    "set": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 1
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyCon",
            "name": "Map",
            "args": [
              {
                "_tag": "TyVar",
                "id": 0
              },
              {
                "_tag": "TyVar",
                "id": 1
              }
            ]
          },
          "to": {
            "_tag": "TyCon",
            "name": "Map",
            "args": [
              {
                "_tag": "TyVar",
                "id": 0
              },
              {
                "_tag": "TyVar",
                "id": 1
              }
            ]
          }
        }
      }
    },
    "delete": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Map",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Map",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "size": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Map",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          },
          {
            "_tag": "TyVar",
            "id": 1
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    },
    "keys": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Map",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          },
          {
            "_tag": "TyVar",
            "id": 1
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      }
    },
    "values": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Map",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          },
          {
            "_tag": "TyVar",
            "id": 1
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyVar",
            "id": 1
          }
        ]
      }
    },
    "get": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Map",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    }
  },
  "Option": {
    "map": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "flatMap": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "mapOr": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 1
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyVar",
            "id": 0
          },
          "to": {
            "_tag": "TyVar",
            "id": 1
          }
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyCon",
            "name": "Option",
            "args": [
              {
                "_tag": "TyVar",
                "id": 0
              }
            ]
          },
          "to": {
            "_tag": "TyVar",
            "id": 1
          }
        }
      }
    },
    "exists": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "contains": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "unwrapOr": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyVar",
          "id": 0
        }
      }
    },
    "orElse": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            }
          ]
        }
      }
    },
    "isSome": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    },
    "isNone": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "Result": {
    "map": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        }
      }
    },
    "mapErr": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 2
        },
        "to": {
          "_tag": "TyVar",
          "id": 1
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 1
            }
          ]
        }
      }
    },
    "flatMap": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyVar",
          "id": 0
        },
        "to": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        }
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 1
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        }
      }
    },
    "unwrapOr": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyVar",
        "id": 0
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Result",
          "args": [
            {
              "_tag": "TyVar",
              "id": 0
            },
            {
              "_tag": "TyVar",
              "id": 2
            }
          ]
        },
        "to": {
          "_tag": "TyVar",
          "id": 0
        }
      }
    },
    "isOk": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Result",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          },
          {
            "_tag": "TyVar",
            "id": 2
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    },
    "isErr": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "Result",
        "args": [
          {
            "_tag": "TyVar",
            "id": 0
          },
          {
            "_tag": "TyVar",
            "id": 2
          }
        ]
      },
      "to": {
        "_tag": "TyCon",
        "name": "bool",
        "args": []
      }
    }
  },
  "Str": {
    "length": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      }
    },
    "concat": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        }
      }
    },
    "toUpper": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      }
    },
    "toLower": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      }
    },
    "trim": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      }
    },
    "split": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyCon",
              "name": "string",
              "args": []
            }
          ]
        }
      }
    },
    "join": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "Array",
          "args": [
            {
              "_tag": "TyCon",
              "name": "string",
              "args": []
            }
          ]
        },
        "to": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        }
      }
    },
    "contains": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "startsWith": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "endsWith": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "bool",
          "args": []
        }
      }
    },
    "slice": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "number",
          "args": []
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyCon",
            "name": "string",
            "args": []
          },
          "to": {
            "_tag": "TyCon",
            "name": "string",
            "args": []
          }
        }
      }
    },
    "replace": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyFn",
          "from": {
            "_tag": "TyCon",
            "name": "string",
            "args": []
          },
          "to": {
            "_tag": "TyCon",
            "name": "string",
            "args": []
          }
        }
      }
    },
    "get": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyCon",
              "name": "string",
              "args": []
            }
          ]
        }
      }
    },
    "codeAt": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyFn",
        "from": {
          "_tag": "TyCon",
          "name": "string",
          "args": []
        },
        "to": {
          "_tag": "TyCon",
          "name": "Option",
          "args": [
            {
              "_tag": "TyCon",
              "name": "number",
              "args": []
            }
          ]
        }
      }
    },
    "fromCode": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "number",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      }
    },
    "chars": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "Array",
        "args": [
          {
            "_tag": "TyCon",
            "name": "string",
            "args": []
          }
        ]
      }
    },
    "toNumber": {
      "_tag": "TyFn",
      "from": {
        "_tag": "TyCon",
        "name": "string",
        "args": []
      },
      "to": {
        "_tag": "TyCon",
        "name": "Option",
        "args": [
          {
            "_tag": "TyCon",
            "name": "number",
            "args": []
          }
        ]
      }
    }
  }
};
const _namespaceRuntime = {
  "Array": {
    "map": "map",
    "filter": "filter",
    "reduce": "reduce",
    "length": "length",
    "head": "_Array_head",
    "get": "_Array_get",
    "find": "_Array_find",
    "reverse": "_Array_reverse",
    "concat": "_Array_concat",
    "append": "_Array_append",
    "prepend": "_Array_prepend",
    "flatMap": "_Array_flatMap",
    "take": "_Array_take",
    "drop": "_Array_drop",
    "tail": "_Array_tail",
    "contains": "_Array_contains",
    "sort": "_Array_sort",
    "sortBy": "_Array_sortBy",
    "dedupe": "_Array_dedupe",
    "dedupeBy": "_Array_dedupeBy",
    "max": "_Array_max",
    "min": "_Array_min",
    "maxBy": "_Array_maxBy",
    "minBy": "_Array_minBy"
  },
  "List": {
    "map": "_List_map",
    "filter": "_List_filter",
    "concat": "_List_concat",
    "flatMap": "_List_flatMap",
    "head": "_List_head"
  },
  "Set": {
    "has": "_Set_has",
    "add": "_Set_add",
    "delete": "_Set_delete",
    "size": "_Set_size",
    "toArray": "_Set_toArray",
    "fromArray": "_Set_fromArray",
    "union": "_Set_union",
    "intersect": "_Set_intersect",
    "diff": "_Set_diff"
  },
  "Map": {
    "has": "_Map_has",
    "getOr": "_Map_getOr",
    "set": "_Map_set",
    "delete": "_Map_delete",
    "size": "_Map_size",
    "keys": "_Map_keys",
    "values": "_Map_values",
    "get": "_Map_get"
  },
  "Option": {
    "map": "_Option_map",
    "flatMap": "_Option_flatMap",
    "mapOr": "_Option_mapOr",
    "exists": "_Option_exists",
    "contains": "_Option_contains",
    "unwrapOr": "_Option_unwrapOr",
    "orElse": "_Option_orElse",
    "isSome": "_Option_isSome",
    "isNone": "_Option_isNone"
  },
  "Result": {
    "map": "_Result_map",
    "mapErr": "_Result_mapErr",
    "flatMap": "_Result_flatMap",
    "unwrapOr": "_Result_unwrapOr",
    "isOk": "_Result_isOk",
    "isErr": "_Result_isErr"
  },
  "Str": {
    "length": "_Str_length",
    "concat": "_Str_concat",
    "toUpper": "_Str_toUpper",
    "toLower": "_Str_toLower",
    "trim": "_Str_trim",
    "split": "_Str_split",
    "join": "_Str_join",
    "contains": "_Str_contains",
    "startsWith": "_Str_startsWith",
    "endsWith": "_Str_endsWith",
    "slice": "_Str_slice",
    "replace": "_Str_replace",
    "get": "_Str_get",
    "codeAt": "_Str_codeAt",
    "fromCode": "_Str_fromCode",
    "chars": "_Str_chars",
    "toNumber": "_Str_toNumber"
  }
};
const _preludeJsDefs = {
  "_list": "const _list = (g) => ({ [Symbol.iterator]: g });",
  "_curry": "const _curry = (n, f) => function c(...a) { if (a.length < n) return (...b) => c(...a, ...b); if (a.length === n) return f(...a); return a.slice(n).reduce((g, x) => g(x), f(...a.slice(0, n))); };",
  "Some": "const Some = (value) => ({ _tag: \"Some\", value });",
  "None": "const None = { _tag: \"None\" };",
  "Ok": "const Ok = (value) => ({ _tag: \"Ok\", value });",
  "Err": "const Err = (error) => ({ _tag: \"Err\", error });",
  "add": "const add = _curry(2, (a, b) => a + b);",
  "sub": "const sub = _curry(2, (a, b) => a - b);",
  "mul": "const mul = _curry(2, (a, b) => a * b);",
  "div": "const div = _curry(2, (a, b) => a / b);",
  "square": "const square = (x) => x * x;",
  "sqrt": "const sqrt = (x) => Math.sqrt(x);",
  "hypot": "const hypot = _curry(2, (a, b) => Math.hypot(a, b));",
  "pi": "const pi = Math.PI;",
  "eq": "const eq = _curry(2, (x, y) => { if (x === y) return true; if (typeof x !== \"object\" || x === null || typeof y !== \"object\" || y === null) return false; const ax = Array.isArray(x); if (ax !== Array.isArray(y)) return false; if (ax) { if (x.length !== y.length) return false; for (let i = 0; i < x.length; i++) if (!eq(x[i], y[i])) return false; return true; } const kx = Object.keys(x), ky = Object.keys(y); if (kx.length !== ky.length) return false; for (const k of kx) if (!eq(x[k], y[k])) return false; return true; });",
  "compare": "const compare = _curry(2, (x, y) => { if (x === y) return 0; const t = typeof x; if (t === \"number\" || t === \"string\" || t === \"boolean\") return x < y ? -1 : x > y ? 1 : 0; if (Array.isArray(x) && Array.isArray(y)) { const n = Math.min(x.length, y.length); for (let i = 0; i < n; i++) { const c = compare(x[i], y[i]); if (c !== 0) return c; } return compare(x.length, y.length); } const sx = JSON.stringify(x), sy = JSON.stringify(y); return sx < sy ? -1 : sx > sy ? 1 : 0; });",
  "show": "const show = (x) => { const t = typeof x; if (t === \"string\") return JSON.stringify(x); if (t !== \"object\" || x === null) return String(x); if (Array.isArray(x)) return \"[\" + x.map(show).join(\", \") + \"]\"; if (typeof x._tag === \"string\") { const ks = Object.keys(x).filter((k) => k !== \"_tag\"); return ks.length === 0 ? x._tag : x._tag + \"(\" + ks.map((k) => show(x[k])).join(\", \") + \")\"; } const ks = Object.keys(x); if (ks.length === 0) return String(x); return \"{ \" + ks.map((k) => k + \": \" + show(x[k])).join(\", \") + \" }\"; };",
  "lt": "const lt = _curry(2, (a, b) => a < b);",
  "gt": "const gt = _curry(2, (a, b) => a > b);",
  "gte": "const gte = _curry(2, (a, b) => a >= b);",
  "lte": "const lte = _curry(2, (a, b) => a <= b);",
  "not": "const not = (b) => !b;",
  "and": "const and = _curry(2, (a, b) => a && b);",
  "or": "const or = _curry(2, (a, b) => a || b);",
  "min": "const min = _curry(2, (a, b) => Math.min(a, b));",
  "max": "const max = _curry(2, (a, b) => Math.max(a, b));",
  "pow": "const pow = _curry(2, (a, b) => a ** b);",
  "mod": "const mod = _curry(2, (a, b) => ((a % b) + b) % b);",
  "abs": "const abs = (x) => Math.abs(x);",
  "floor": "const floor = (x) => Math.floor(x);",
  "ceil": "const ceil = (x) => Math.ceil(x);",
  "round": "const round = (x) => Math.round(x);",
  "sign": "const sign = (x) => Math.sign(x);",
  "negate": "const negate = (x) => -x;",
  "length": "const length = (xs) => xs.length;",
  "map": "const map = _curry(2, (f, xs) => xs.map((x) => f(x)));",
  "filter": "const filter = _curry(2, (f, xs) => xs.filter((x) => f(x)));",
  "reduce": "const reduce = _curry(3, (f, init, xs) => xs.reduce((acc, x) => f(acc)(x), init));",
  "identity": "const identity = (x) => x;",
  "always": "const always = _curry(2, (x, _y) => x);",
  "compose": "const compose = _curry(3, (f, g, x) => f(g(x)));",
  "capitalize": "const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);",
  "range": "const range = _curry(2, (lo, hi) => _list(function* () { for (let i = lo; i < hi; i++) yield i; }));",
  "iterate": "const iterate = _curry(2, (f, x) => _list(function* () { let v = x; for (;;) { yield v; v = f(v); } }));",
  "repeat": "const repeat = (x) => _list(function* () { for (;;) yield x; });",
  "take": "const take = _curry(2, (n, xs) => _list(function* () { let i = 0; for (const x of xs) { if (i >= n) break; yield x; i++; } }));",
  "takeWhile": "const takeWhile = _curry(2, (p, xs) => _list(function* () { for (const x of xs) { if (!p(x)) break; yield x; } }));",
  "drop": "const drop = _curry(2, (n, xs) => _list(function* () { let i = 0; for (const x of xs) { if (i < n) { i++; continue; } yield x; } }));",
  "fromArray": "const fromArray = (xs) => _list(function* () { yield* xs; });",
  "toArray": "const toArray = (xs) => [...xs];",
  "_List_map": "const _List_map = _curry(2, (f, xs) => _list(function* () { for (const x of xs) yield f(x); }));",
  "_List_filter": "const _List_filter = _curry(2, (p, xs) => _list(function* () { for (const x of xs) if (p(x)) yield x; }));",
  "_List_concat": "const _List_concat = _curry(2, (xs, ys) => _list(function* () { yield* xs; yield* ys; }));",
  "_List_flatMap": "const _List_flatMap = _curry(2, (f, xs) => _list(function* () { for (const x of xs) yield* f(x); }));",
  "_Set_has": "const _Set_has = _curry(2, (x, s) => s.has(x));",
  "_Set_add": "const _Set_add = _curry(2, (x, s) => new Set(s).add(x));",
  "_Set_delete": "const _Set_delete = _curry(2, (x, s) => { const n = new Set(s); n.delete(x); return n; });",
  "_Set_size": "const _Set_size = (s) => s.size;",
  "_Set_toArray": "const _Set_toArray = (s) => [...s];",
  "_Set_fromArray": "const _Set_fromArray = (xs) => new Set(xs);",
  "_Set_union": "const _Set_union = _curry(2, (a, b) => new Set([...a, ...b]));",
  "_Set_intersect": "const _Set_intersect = _curry(2, (a, b) => new Set([...a].filter((x) => b.has(x))));",
  "_Set_diff": "const _Set_diff = _curry(2, (a, b) => new Set([...a].filter((x) => !b.has(x))));",
  "_Map_has": "const _Map_has = _curry(2, (k, m) => m.has(k));",
  "_Map_getOr": "const _Map_getOr = _curry(3, (d, k, m) => (m.has(k) ? m.get(k) : d));",
  "_Map_set": "const _Map_set = _curry(3, (k, v, m) => { const n = new Map(m); n.set(k, v); return n; });",
  "_Map_delete": "const _Map_delete = _curry(2, (k, m) => { const n = new Map(m); n.delete(k); return n; });",
  "_Map_size": "const _Map_size = (m) => m.size;",
  "_Map_keys": "const _Map_keys = (m) => [...m.keys()];",
  "_Map_values": "const _Map_values = (m) => [...m.values()];",
  "_Map_get": "const _Map_get = _curry(2, (k, m) => (m.has(k) ? Some(m.get(k)) : None));",
  "_Option_map": "const _Option_map = _curry(2, (f, o) => (o._tag === \"Some\" ? Some(f(o.value)) : None));",
  "_Option_flatMap": "const _Option_flatMap = _curry(2, (f, o) => (o._tag === \"Some\" ? f(o.value) : None));",
  "_Option_mapOr": "const _Option_mapOr = _curry(3, (d, f, o) => (o._tag === \"Some\" ? f(o.value) : d));",
  "_Option_exists": "const _Option_exists = _curry(2, (p, o) => o._tag === \"Some\" && p(o.value));",
  "_Option_contains": "const _Option_contains = _curry(2, (x, o) => o._tag === \"Some\" && eq(x, o.value));",
  "_Option_unwrapOr": "const _Option_unwrapOr = _curry(2, (d, o) => (o._tag === \"Some\" ? o.value : d));",
  "_Option_orElse": "const _Option_orElse = _curry(2, (fb, o) => (o._tag === \"Some\" ? o : fb));",
  "_Option_isSome": "const _Option_isSome = (o) => o._tag === \"Some\";",
  "_Option_isNone": "const _Option_isNone = (o) => o._tag === \"None\";",
  "_Result_map": "const _Result_map = _curry(2, (f, r) => (r._tag === \"Ok\" ? Ok(f(r.value)) : r));",
  "_Result_mapErr": "const _Result_mapErr = _curry(2, (f, r) => (r._tag === \"Err\" ? Err(f(r.error)) : r));",
  "_Result_flatMap": "const _Result_flatMap = _curry(2, (f, r) => (r._tag === \"Ok\" ? f(r.value) : r));",
  "_Result_unwrapOr": "const _Result_unwrapOr = _curry(2, (d, r) => (r._tag === \"Ok\" ? r.value : d));",
  "_Result_isOk": "const _Result_isOk = (r) => r._tag === \"Ok\";",
  "_Result_isErr": "const _Result_isErr = (r) => r._tag === \"Err\";",
  "_List_head": "const _List_head = (xs) => { for (const x of xs) return Some(x); return None; };",
  "_Array_head": "const _Array_head = (xs) => (xs.length > 0 ? Some(xs[0]) : None);",
  "_Array_get": "const _Array_get = _curry(2, (i, xs) => (i >= 0 && i < xs.length ? Some(xs[i]) : None));",
  "_Array_find": "const _Array_find = _curry(2, (p, xs) => { for (const x of xs) if (p(x)) return Some(x); return None; });",
  "_Array_reverse": "const _Array_reverse = (xs) => [...xs].reverse();",
  "_Array_concat": "const _Array_concat = _curry(2, (xs, ys) => xs.concat(ys));",
  "_Array_append": "const _Array_append = _curry(2, (x, xs) => [...xs, x]);",
  "_Array_prepend": "const _Array_prepend = _curry(2, (x, xs) => [x, ...xs]);",
  "_Array_flatMap": "const _Array_flatMap = _curry(2, (f, xs) => xs.flatMap((x) => f(x)));",
  "_Array_take": "const _Array_take = _curry(2, (n, xs) => xs.slice(0, n));",
  "_Array_drop": "const _Array_drop = _curry(2, (n, xs) => xs.slice(n));",
  "_Array_tail": "const _Array_tail = (xs) => xs.slice(1);",
  "_Array_contains": "const _Array_contains = _curry(2, (x, xs) => xs.some((y) => eq(x, y)));",
  "_Array_sort": "const _Array_sort = (xs) => [...xs].sort(compare);",
  "_Array_sortBy": "const _Array_sortBy = _curry(2, (f, xs) => [...xs].sort((a, b) => compare(f(a), f(b))));",
  "_Array_dedupe": "const _Array_dedupe = (xs) => xs.filter((x, i) => xs.findIndex((y) => eq(x, y)) === i);",
  "_Array_dedupeBy": "const _Array_dedupeBy = _curry(2, (f, xs) => { const seen = []; return xs.filter((x) => { const k = f(x); if (seen.some((s) => eq(s, k))) return false; seen.push(k); return true; }); });",
  "_Array_max": "const _Array_max = (xs) => xs.length ? Some(xs.reduce((a, b) => compare(a, b) >= 0 ? a : b)) : None;",
  "_Array_min": "const _Array_min = (xs) => xs.length ? Some(xs.reduce((a, b) => compare(a, b) <= 0 ? a : b)) : None;",
  "_Array_maxBy": "const _Array_maxBy = _curry(2, (f, xs) => xs.length ? Some(xs.reduce((a, b) => compare(f(a), f(b)) >= 0 ? a : b)) : None);",
  "_Array_minBy": "const _Array_minBy = _curry(2, (f, xs) => xs.length ? Some(xs.reduce((a, b) => compare(f(a), f(b)) <= 0 ? a : b)) : None);",
  "_Str_length": "const _Str_length = (s) => s.length;",
  "_Str_concat": "const _Str_concat = _curry(2, (a, b) => a + b);",
  "_Str_toUpper": "const _Str_toUpper = (s) => s.toUpperCase();",
  "_Str_toLower": "const _Str_toLower = (s) => s.toLowerCase();",
  "_Str_trim": "const _Str_trim = (s) => s.trim();",
  "_Str_split": "const _Str_split = _curry(2, (sep, s) => s.split(sep));",
  "_Str_join": "const _Str_join = _curry(2, (sep, xs) => xs.join(sep));",
  "_Str_contains": "const _Str_contains = _curry(2, (needle, s) => s.includes(needle));",
  "_Str_startsWith": "const _Str_startsWith = _curry(2, (p, s) => s.startsWith(p));",
  "_Str_endsWith": "const _Str_endsWith = _curry(2, (p, s) => s.endsWith(p));",
  "_Str_slice": "const _Str_slice = _curry(3, (start, end, s) => s.slice(start, end));",
  "_Str_replace": "const _Str_replace = _curry(3, (find, repl, s) => s.replaceAll(find, repl));",
  "_Str_get": "const _Str_get = _curry(2, (i, s) => (i >= 0 && i < s.length ? Some(s[i]) : None));",
  "_Str_codeAt": "const _Str_codeAt = _curry(2, (i, s) => (i >= 0 && i < s.length ? Some(s.charCodeAt(i)) : None));",
  "_Str_fromCode": "const _Str_fromCode = (n) => String.fromCharCode(n);",
  "_Str_chars": "const _Str_chars = (s) => [...s];",
  "_Str_toNumber": "const _Str_toNumber = (s) => { const n = Number(s); return Number.isNaN(n) ? None : Some(n); };"
};
const _runtimeDeps = {
  "add": [
    "_curry"
  ],
  "sub": [
    "_curry"
  ],
  "mul": [
    "_curry"
  ],
  "div": [
    "_curry"
  ],
  "hypot": [
    "_curry"
  ],
  "eq": [
    "_curry"
  ],
  "compare": [
    "_curry"
  ],
  "lt": [
    "_curry"
  ],
  "gt": [
    "_curry"
  ],
  "min": [
    "_curry"
  ],
  "max": [
    "_curry"
  ],
  "pow": [
    "_curry"
  ],
  "mod": [
    "_curry"
  ],
  "map": [
    "_curry"
  ],
  "filter": [
    "_curry"
  ],
  "reduce": [
    "_curry"
  ],
  "always": [
    "_curry"
  ],
  "compose": [
    "_curry"
  ],
  "range": [
    "_list",
    "_curry"
  ],
  "iterate": [
    "_list",
    "_curry"
  ],
  "repeat": [
    "_list"
  ],
  "take": [
    "_list",
    "_curry"
  ],
  "takeWhile": [
    "_list",
    "_curry"
  ],
  "drop": [
    "_list",
    "_curry"
  ],
  "fromArray": [
    "_list"
  ],
  "_List_map": [
    "_list",
    "_curry"
  ],
  "_List_filter": [
    "_list",
    "_curry"
  ],
  "_List_concat": [
    "_list",
    "_curry"
  ],
  "_List_flatMap": [
    "_list",
    "_curry"
  ],
  "_Set_has": [
    "_curry"
  ],
  "_Set_add": [
    "_curry"
  ],
  "_Set_delete": [
    "_curry"
  ],
  "_Set_union": [
    "_curry"
  ],
  "_Set_intersect": [
    "_curry"
  ],
  "_Set_diff": [
    "_curry"
  ],
  "_Map_has": [
    "_curry"
  ],
  "_Map_getOr": [
    "_curry"
  ],
  "_Map_set": [
    "_curry"
  ],
  "_Map_delete": [
    "_curry"
  ],
  "_Map_get": [
    "Some",
    "None",
    "_curry"
  ],
  "gte": [
    "_curry"
  ],
  "lte": [
    "_curry"
  ],
  "and": [
    "_curry"
  ],
  "or": [
    "_curry"
  ],
  "_Option_map": [
    "Some",
    "None",
    "_curry"
  ],
  "_Option_flatMap": [
    "None",
    "_curry"
  ],
  "_Option_mapOr": [
    "_curry"
  ],
  "_Option_exists": [
    "_curry"
  ],
  "_Option_contains": [
    "eq",
    "_curry"
  ],
  "_Option_unwrapOr": [
    "_curry"
  ],
  "_Option_orElse": [
    "_curry"
  ],
  "_Result_map": [
    "Ok",
    "_curry"
  ],
  "_Result_mapErr": [
    "Err",
    "_curry"
  ],
  "_Result_flatMap": [
    "_curry"
  ],
  "_Result_unwrapOr": [
    "_curry"
  ],
  "_List_head": [
    "Some",
    "None"
  ],
  "_Array_head": [
    "Some",
    "None"
  ],
  "_Array_get": [
    "Some",
    "None",
    "_curry"
  ],
  "_Array_find": [
    "Some",
    "None",
    "_curry"
  ],
  "_Array_concat": [
    "_curry"
  ],
  "_Array_append": [
    "_curry"
  ],
  "_Array_prepend": [
    "_curry"
  ],
  "_Array_flatMap": [
    "_curry"
  ],
  "_Array_take": [
    "_curry"
  ],
  "_Array_drop": [
    "_curry"
  ],
  "_Array_contains": [
    "eq",
    "_curry"
  ],
  "_Array_dedupe": [
    "eq"
  ],
  "_Array_dedupeBy": [
    "eq",
    "_curry"
  ],
  "_Array_sort": [
    "compare"
  ],
  "_Array_sortBy": [
    "compare",
    "_curry"
  ],
  "_Array_max": [
    "compare",
    "Some",
    "None"
  ],
  "_Array_min": [
    "compare",
    "Some",
    "None"
  ],
  "_Array_maxBy": [
    "compare",
    "Some",
    "None",
    "_curry"
  ],
  "_Array_minBy": [
    "compare",
    "Some",
    "None",
    "_curry"
  ],
  "_Str_concat": [
    "_curry"
  ],
  "_Str_split": [
    "_curry"
  ],
  "_Str_join": [
    "_curry"
  ],
  "_Str_contains": [
    "_curry"
  ],
  "_Str_startsWith": [
    "_curry"
  ],
  "_Str_endsWith": [
    "_curry"
  ],
  "_Str_slice": [
    "_curry"
  ],
  "_Str_replace": [
    "_curry"
  ],
  "_Str_get": [
    "Some",
    "None",
    "_curry"
  ],
  "_Str_codeAt": [
    "Some",
    "None",
    "_curry"
  ],
  "_Str_toNumber": [
    "Some",
    "None"
  ]
};

const _map = (o) => new Map(Object.entries(o));
const _mapmap = (o) => new Map(Object.entries(o).map(([k, v]) => [k, _map(v)]));

// name -> Ty  (for the inferrer's builtin environment)
export const builtins = _map(_builtins);
// namespace -> (member -> Ty)  (for namespaced builtins, e.g. Array.map)
export const namespaces = _mapmap(_namespaces);
// namespace -> (member -> emitted JS)  (codegen)
export const namespaceRuntime = _mapmap(_namespaceRuntime);
// name -> emitted JS runtime definition  (codegen)
export const preludeJsDefs = _map(_preludeJsDefs);
// name -> [dependency names]  (codegen runtime-dependency graph)
export const runtimeDeps = _map(_runtimeDeps);
