import type { SeedCompile } from "./compile-host-types";
export declare const compile: SeedCompile["compile"];
export declare const compileTs: SeedCompile["compileTs"];
export declare const inferTypes: SeedCompile["inferTypes"];
export declare const compileWith: SeedCompile["compileWith"];
export declare const compileTsWith: SeedCompile["compileTsWith"];
export declare const inferTypesWith: SeedCompile["inferTypesWith"];
export declare const inferTypesRecoveringWith: SeedCompile["inferTypesRecoveringWith"];
export declare const nominalTypeName: SeedCompile["nominalTypeName"];
export declare const symbolIndexSync: SeedCompile["symbolIndexSync"];
export declare const runtimeAnnotation: SeedCompile["runtimeAnnotation"];
export declare const compileTargetsWith: SeedCompile["compileTargetsWith"];
export declare const emitDtsTextWith: SeedCompile["emitDtsTextWith"];
