// Generated by scripts/freeze-seed.ts — do not edit.
import type { Option, Result } from "@mochi/compiler/runtime";
export type Expr =
  | { _tag: "ENum"; value: number; raw: string; span: Span }
  | { _tag: "EUnit"; span: Span }
  | { _tag: "EBool"; value: boolean; span: Span }
  | { _tag: "EStr"; value: string; span: Span }
  | { _tag: "ERef"; name: string; span: Span }
  | { _tag: "ECall"; fn: Expr; args: Expr[]; origin: Option<string>; span: Span }
  | { _tag: "ELambda"; params: LamParam[]; body: Expr; span: Span }
  | {
      _tag: "ELetIn";
      name: string;
      nameSpan: Span;
      annot: Option<TypeExpr>;
      value: Expr;
      body: Expr;
      span: Span;
    }
  | {
      _tag: "ELetBind";
      param: LamParam;
      paramSpan: Span;
      monad: string;
      value: Expr;
      body: Expr;
      span: Span;
    }
  | { _tag: "EPipe"; left: Expr; right: Expr; fast: boolean; span: Span }
  | { _tag: "EDo"; exprs: Expr[]; span: Span }
  | { _tag: "ETernary"; cond: Expr; thenE: Expr; elseE: Expr; span: Span }
  | { _tag: "EMatch"; scrutinee: Expr; arms: MatchArm[]; span: Span }
  | { _tag: "ERecord"; fields: Field[]; spread: Option<Expr>; span: Span }
  | { _tag: "EField"; target: Expr; name: string; optional: boolean; span: Span }
  | { _tag: "ETuple"; elements: Expr[]; span: Span }
  | { _tag: "EArr"; elements: SeqElem[]; span: Span }
  | { _tag: "EList"; elements: SeqElem[]; span: Span }
  | { _tag: "ESet"; elements: SeqElem[]; span: Span }
  | { _tag: "EMap"; entries: MapEntry[]; span: Span }
  | { _tag: "ELoop"; params: LoopParam[]; body: Expr; span: Span }
  | { _tag: "ERecur"; args: Expr[]; span: Span }
  | { _tag: "EInterp"; parts: InterpPart[]; span: Span };
export type Span = { start: number; end: number };
export type LamParam =
  | { _tag: "LPName"; name: string; annot: Option<TypeExpr> }
  | { _tag: "LPRecord"; fields: string[] }
  | { _tag: "LPTuple"; names: string[] }
  | {
      _tag: "LPLabeled";
      name: string;
      annot: Option<TypeExpr>;
      optional: boolean;
      defaultValue: Option<Expr>;
    }
  | { _tag: "LPSpanned"; param: LamParam; nameSpans: Span[] };
export type TypeExpr =
  | { _tag: "TyName"; name: string; span: Span }
  | { _tag: "TyArrow"; from: TypeExpr; to: TypeExpr; span: Span }
  | { _tag: "TyApp"; ctor: string; args: TypeExpr[]; span: Span }
  | { _tag: "TyTuple"; elems: TypeExpr[]; span: Span }
  | { _tag: "TyList"; elem: TypeExpr; span: Span }
  | { _tag: "TyQual"; alias: string; name: string; nameSpan: Span; args: TypeExpr[]; span: Span }
  | { _tag: "TyLit"; value: string; span: Span }
  | { _tag: "TyUnion"; members: TypeExpr[]; span: Span };
export type MatchArm = { pattern: Pattern; guard: Option<Expr>; body: Expr };
export type Pattern =
  | { _tag: "PWild"; span: Span }
  | { _tag: "PUnit"; span: Span }
  | { _tag: "PBind"; name: string; span: Span }
  | { _tag: "PAs"; pat: Pattern; name: string; nameSpan: Span; span: Span }
  | { _tag: "PLit"; value: number; raw: string; span: Span }
  | { _tag: "PBool"; value: boolean; span: Span }
  | { _tag: "PStr"; value: string; span: Span }
  | { _tag: "PTuple"; elems: Pattern[]; span: Span }
  | { _tag: "PRecord"; fields: PatField[]; span: Span }
  | { _tag: "PCtor"; ctor: string; args: Pattern[]; ns: Option<string>; span: Span }
  | { _tag: "PArr"; elems: Pattern[]; rest: Option<Pattern>; span: Span }
  | { _tag: "PList"; elems: Pattern[]; rest: Option<Pattern>; span: Span }
  | { _tag: "POr"; alts: Pattern[]; span: Span };
export type PatField = { label: string; pat: Pattern };
export type Field = { name: string; value: Expr };
export type SeqElem = { _tag: "SEExpr"; expr: Expr } | { _tag: "SESpread"; expr: Expr };
export type MapEntry = { key: Expr; value: Expr };
export type LoopParam = { name: string; nameSpan: Span; init: Expr };
export type InterpPart = { _tag: "IPLit"; value: string } | { _tag: "IPExpr"; expr: Expr };
export type Stmt =
  | {
      _tag: "SLet";
      name: string;
      nameSpan: Span;
      annot: Option<TypeExpr>;
      value: Expr;
      exported: boolean;
      doc: Option<string>;
      span: Span;
    }
  | {
      _tag: "SType";
      name: string;
      params: string[];
      ctors: Ctor[];
      alias: Option<AliasField[]>;
      aliasType: Option<TypeExpr>;
      exported: boolean;
      doc: Option<string>;
      span: Span;
    }
  | {
      _tag: "SExtern";
      name: string;
      nameSpan: Span;
      params: string[];
      typeExpr: TypeExpr;
      module: string;
      imported: string;
      curried: boolean;
      exported: boolean;
      doc: Option<string>;
      span: Span;
    }
  | { _tag: "SImport"; names: Name[]; from: string; span: Span }
  | { _tag: "SImportNs"; alias: Name; from: string; span: Span }
  | { _tag: "SExpr"; value: Expr; span: Span }
  | { _tag: "SError"; span: Span };
export type Ctor = { name: string; fields: CtorField[]; span: Span };
export type CtorField = { name: Option<string>; fieldType: TypeExpr };
export type AliasField = { name: string; fieldType: TypeExpr; optional: boolean };
export type Name = { name: string; span: Span };
export type IErr = {
  message: string;
  start: number;
  end: number;
  help: Option<string>;
  suggestions: Suggestion[];
};
export type Suggestion = { title: string; start: number; end: number; replaceWith: string };
export type InferApi = {
  inferExpr: (a: Expr, b: St) => Result<[Ty, St], IErr>;
  unify: (a: Ty, b: Ty, c: St, d: SpanAt) => Result<St, IErr>;
};
export type St = {
  tv: Map<number, Ty>;
  rv: Map<number, Row>;
  next: number;
  recorded: TypeAt[];
  letSpans: Map<string, SpanAt>;
  letUses: Map<string, Ty[]>;
};
export type Ty =
  | { _tag: "TyVar"; id: number }
  | { _tag: "TyCon"; name: string; args: Ty[] }
  | { _tag: "TyFn"; from: Ty; to: Ty }
  | { _tag: "TyRecord"; row: Row }
  | { _tag: "TySingleton"; base: string; value: string }
  | { _tag: "TyOneOf"; members: Ty[] };
export type Row =
  | { _tag: "RowEmpty" }
  | { _tag: "RowVar"; id: number }
  | { _tag: "RowExtend"; label: string; fieldType: Ty; optional: boolean; rest: Row };
export type TypeAt = { span: SpanAt; ty: Ty };
export type SpanAt = { start: number; end: number };
export type LocTok<A> = { tok: A; start: number; end: number; doc: Option<string> };
export type TsApi = { tsType: (a: Ty) => string; aliasOf: (a: Row) => Option<string> };
export type Tok =
  | { _tag: "TLet" }
  | { _tag: "TType" }
  | { _tag: "TExtern" }
  | { _tag: "TSwitch" }
  | { _tag: "TLoop" }
  | { _tag: "TRecur" }
  | { _tag: "TDo" }
  | { _tag: "TImport" }
  | { _tag: "TExport" }
  | { _tag: "TEq" }
  | { _tag: "TArrow" }
  | { _tag: "TTarrow" }
  | { _tag: "TPipe" }
  | { _tag: "TCompose" }
  | { _tag: "TConcat" }
  | { _tag: "TBar" }
  | { _tag: "TLparen" }
  | { _tag: "TRparen" }
  | { _tag: "TLbrace" }
  | { _tag: "TRbrace" }
  | { _tag: "TLbracket" }
  | { _tag: "TRbracket" }
  | { _tag: "TSpread" }
  | { _tag: "TPlus" }
  | { _tag: "TMinus" }
  | { _tag: "TStar" }
  | { _tag: "TSlash" }
  | { _tag: "TPercent" }
  | { _tag: "TAt" }
  | { _tag: "THash" }
  | { _tag: "TTilde" }
  | { _tag: "TDot" }
  | { _tag: "TColon" }
  | { _tag: "TQuestion" }
  | { _tag: "TEqeq" }
  | { _tag: "TNeq" }
  | { _tag: "TLte" }
  | { _tag: "TGte" }
  | { _tag: "TLt" }
  | { _tag: "TGt" }
  | { _tag: "TAndand" }
  | { _tag: "TOror" }
  | { _tag: "TBang" }
  | { _tag: "TBacktick" }
  | { _tag: "TComma" }
  | { _tag: "TSemi" }
  | { _tag: "TNum"; value: number; raw: string }
  | { _tag: "TBool"; value: boolean }
  | { _tag: "TStr"; value: string }
  | { _tag: "TTmplStart"; value: string }
  | { _tag: "TTmplMid"; value: string }
  | { _tag: "TTmplEnd"; value: string }
  | { _tag: "TId"; value: string }
  | { _tag: "TEof" };
