// Generated by scripts/freeze-seed.ts — do not edit.
import type { Option, Result } from "@mochi/compiler/runtime";
type HostFn<A extends unknown[], R> = (...args: A) => R;
export type Opts = {
  open: boolean;
  runtime: boolean;
  docs: boolean;
  moduleExt: string;
  strictEntry: boolean;
  plugins: Option<HostPlugin[]>;
  dtsTypeNames: Map<string, string>;
};
export type HostPlugin = {
  name: string;
  parse: Option<
    (
      a: LocTok[],
      b: number,
      c: (a: LocTok[], b: number) => Result<[Expr, number], PErr>,
    ) => Result<Option<[Expr, number]>, PErr>
  >;
  inferCall: Option<
    (a: Expr, b: Expr[], c: Option<string>, d: St, e: InferApi) => Result<Option<[Ty, St]>, IErr>
  >;
  format: Option<(a: Expr) => Option<Expr>>;
  formatDoc: Option<(a: Expr, b: FormatApi) => Option<Doc>>;
  dtsBinding: Option<(a: string, b: Expr, c: Ty, d: TsApi) => Option<string>>;
  bindingType: Option<(a: Expr, b: Ty, c: TsApi) => Option<string>>;
};
export type LocTok = { tok: Tok; start: number; end: number; doc: Option<string> };
export type Tok =
  | { _tag: "TLet" }
  | { _tag: "TType" }
  | { _tag: "TExtern" }
  | { _tag: "TSwitch" }
  | { _tag: "TLoop" }
  | { _tag: "TRecur" }
  | { _tag: "TDo" }
  | { _tag: "TImport" }
  | { _tag: "TExport" }
  | { _tag: "TEq" }
  | { _tag: "TArrow" }
  | { _tag: "TTarrow" }
  | { _tag: "TPipe" }
  | { _tag: "TConcat" }
  | { _tag: "TBar" }
  | { _tag: "TLparen" }
  | { _tag: "TRparen" }
  | { _tag: "TLbrace" }
  | { _tag: "TRbrace" }
  | { _tag: "TLbracket" }
  | { _tag: "TRbracket" }
  | { _tag: "TSpread" }
  | { _tag: "TPlus" }
  | { _tag: "TMinus" }
  | { _tag: "TStar" }
  | { _tag: "TSlash" }
  | { _tag: "TPercent" }
  | { _tag: "TAt" }
  | { _tag: "THash" }
  | { _tag: "TTilde" }
  | { _tag: "TDot" }
  | { _tag: "TColon" }
  | { _tag: "TQuestion" }
  | { _tag: "TEqeq" }
  | { _tag: "TNeq" }
  | { _tag: "TLte" }
  | { _tag: "TGte" }
  | { _tag: "TLt" }
  | { _tag: "TGt" }
  | { _tag: "TAndand" }
  | { _tag: "TOror" }
  | { _tag: "TBang" }
  | { _tag: "TBacktick" }
  | { _tag: "TComma" }
  | { _tag: "TSemi" }
  | { _tag: "TNum"; value: number; raw: string }
  | { _tag: "TBool"; value: boolean }
  | { _tag: "TStr"; value: string }
  | { _tag: "TTmplStart"; value: string }
  | { _tag: "TTmplMid"; value: string }
  | { _tag: "TTmplEnd"; value: string }
  | { _tag: "TId"; value: string }
  | { _tag: "TEof" };
export type Expr =
  | { _tag: "ENum"; value: number; raw: string; span: Span }
  | { _tag: "EUnit"; span: Span }
  | { _tag: "EBool"; value: boolean; span: Span }
  | { _tag: "EStr"; value: string; span: Span }
  | { _tag: "ERef"; name: string; span: Span }
  | { _tag: "ECall"; fn: Expr; args: Expr[]; origin: Option<string>; span: Span }
  | { _tag: "ELambda"; params: LamParam[]; body: Expr; span: Span }
  | {
      _tag: "ELetIn";
      name: string;
      nameSpan: Span;
      annot: Option<TypeExpr>;
      value: Expr;
      body: Expr;
      span: Span;
    }
  | {
      _tag: "ELetBind";
      param: LamParam;
      paramSpan: Span;
      monad: string;
      value: Expr;
      body: Expr;
      span: Span;
    }
  | { _tag: "EPipe"; left: Expr; right: Expr; fast: boolean; span: Span }
  | { _tag: "EDo"; exprs: Expr[]; span: Span }
  | { _tag: "ETernary"; cond: Expr; thenE: Expr; elseE: Expr; span: Span }
  | { _tag: "EMatch"; scrutinee: Expr; arms: MatchArm[]; span: Span }
  | { _tag: "ERecord"; fields: Field[]; spread: Option<Expr>; span: Span }
  | { _tag: "EField"; target: Expr; name: string; optional: boolean; span: Span }
  | { _tag: "ETuple"; elements: Expr[]; span: Span }
  | { _tag: "EArr"; elements: SeqElem[]; span: Span }
  | { _tag: "EList"; elements: SeqElem[]; span: Span }
  | { _tag: "ESet"; elements: SeqElem[]; span: Span }
  | { _tag: "EMap"; entries: MapEntry[]; span: Span }
  | { _tag: "ELoop"; params: LoopParam[]; body: Expr; span: Span }
  | { _tag: "ERecur"; args: Expr[]; span: Span }
  | { _tag: "EInterp"; parts: InterpPart[]; span: Span };
export type Span = { start: number; end: number };
export type LamParam =
  | { _tag: "LPName"; name: string; annot: Option<TypeExpr> }
  | { _tag: "LPRecord"; fields: string[] }
  | { _tag: "LPTuple"; names: string[] }
  | {
      _tag: "LPLabeled";
      name: string;
      annot: Option<TypeExpr>;
      optional: boolean;
      defaultValue: Option<Expr>;
    }
  | { _tag: "LPSpanned"; param: LamParam; nameSpans: Span[] };
export type TypeExpr =
  | { _tag: "TyName"; name: string; span: Span }
  | { _tag: "TyArrow"; from: TypeExpr; to: TypeExpr; span: Span }
  | { _tag: "TyApp"; ctor: string; args: TypeExpr[]; span: Span }
  | { _tag: "TyTuple"; elems: TypeExpr[]; span: Span }
  | { _tag: "TyList"; elem: TypeExpr; span: Span }
  | { _tag: "TyQual"; alias: string; name: string; nameSpan: Span; args: TypeExpr[]; span: Span }
  | { _tag: "TyLit"; value: string; span: Span }
  | { _tag: "TyUnion"; members: TypeExpr[]; span: Span };
export type MatchArm = { pattern: Pattern; guard: Option<Expr>; body: Expr };
export type Pattern =
  | { _tag: "PWild"; span: Span }
  | { _tag: "PUnit"; span: Span }
  | { _tag: "PBind"; name: string; span: Span }
  | { _tag: "PAs"; pat: Pattern; name: string; nameSpan: Span; span: Span }
  | { _tag: "PLit"; value: number; raw: string; span: Span }
  | { _tag: "PBool"; value: boolean; span: Span }
  | { _tag: "PStr"; value: string; span: Span }
  | { _tag: "PTuple"; elems: Pattern[]; span: Span }
  | { _tag: "PRecord"; fields: PatField[]; span: Span }
  | { _tag: "PCtor"; ctor: string; args: Pattern[]; ns: Option<string>; span: Span }
  | { _tag: "PArr"; elems: Pattern[]; rest: Option<Pattern>; span: Span }
  | { _tag: "PList"; elems: Pattern[]; rest: Option<Pattern>; span: Span }
  | { _tag: "POr"; alts: Pattern[]; span: Span };
export type PatField = { label: string; labelSpan: Span; pat: Pattern };
export type Field = { name: string; nameSpan: Span; value: Expr };
export type SeqElem = { _tag: "SEExpr"; expr: Expr } | { _tag: "SESpread"; expr: Expr };
export type MapEntry = { key: Expr; value: Expr };
export type LoopParam = { name: string; nameSpan: Span; init: Expr };
export type InterpPart = { _tag: "IPLit"; value: string } | { _tag: "IPExpr"; expr: Expr };
export type PErr = { message: string; start: number; end: number };
export type St = {
  tv: Map<number, Map<number, Ty>>;
  rv: Map<number, Map<number, Row>>;
  next: number;
  recorded: Recorded;
  letSpans: Map<string, SpanAt>;
  letUses: Map<string, Ty[]>;
};
export type Ty =
  | { _tag: "TyVar"; id: number }
  | { _tag: "TyCon"; name: string; args: Ty[] }
  | { _tag: "TyFn"; from: Ty; to: Ty }
  | { _tag: "TyRecord"; row: Row }
  | { _tag: "TySingleton"; base: string; value: string }
  | { _tag: "TyOneOf"; members: Ty[] };
export type Row =
  | { _tag: "RowEmpty" }
  | { _tag: "RowVar"; id: number }
  | { _tag: "RowExtend"; label: string; fieldType: Ty; optional: boolean; rest: Row };
export type Recorded = { cur: TypeAt[]; full: TypeAt[][] };
export type TypeAt = { span: SpanAt; ty: Ty; sym: Option<BinderSym> };
export type SpanAt = { start: number; end: number };
export type BinderSym = { kind: string; name: string; doc: Option<string> };
export type InferApi = {
  inferExpr: (a: Expr, b: St) => Result<[Ty, St], IErr>;
  unify: (a: Ty, b: Ty, c: St, d: SpanAt) => Result<St, IErr>;
};
export type IErr = {
  message: string;
  start: number;
  end: number;
  help: Option<string>;
  suggestions: Suggestion[];
};
export type Suggestion = { title: string; start: number; end: number; replaceWith: string };
export type FormatApi = {
  exprD: (a: Expr) => Doc;
  memberD: (a: Expr) => Doc;
  flat: (a: Doc) => string;
  strLit: (a: string) => string;
  sourceText: (a: number, b: number) => string;
};
export type Doc =
  | { _tag: "DText"; s: string }
  | { _tag: "DVerbatim"; s: string }
  | { _tag: "DLine"; hard: boolean; soft: boolean }
  | { _tag: "DCat"; parts: Doc[] }
  | { _tag: "DIndent"; doc: Doc }
  | { _tag: "DGroup"; doc: Doc; breaks: boolean }
  | { _tag: "DLineSuffix"; doc: Doc }
  | { _tag: "DBreakParent" };
export type TsApi = { tsType: (a: Ty) => string; aliasOf: (a: Row) => Option<string> };
export type ModuleOutput = { path: string; js: string };
export type MErr = { kind: string; message: string; start: number; end: number };
export type Loaded = { path: string; src: string; stmts: Stmt[] };
export type Stmt =
  | {
      _tag: "SLet";
      name: string;
      nameSpan: Span;
      annot: Option<TypeExpr>;
      value: Expr;
      exported: boolean;
      doc: Option<string>;
      span: Span;
    }
  | {
      _tag: "SType";
      name: string;
      nameSpan: Span;
      params: string[];
      ctors: Ctor[];
      alias: Option<AliasField[]>;
      aliasType: Option<TypeExpr>;
      exported: boolean;
      doc: Option<string>;
      span: Span;
    }
  | {
      _tag: "SExtern";
      name: string;
      nameSpan: Span;
      params: string[];
      typeExpr: TypeExpr;
      module: string;
      imported: string;
      curried: boolean;
      exported: boolean;
      doc: Option<string>;
      span: Span;
    }
  | { _tag: "SImport"; names: Name[]; from: string; span: Span }
  | { _tag: "SImportNs"; alias: Name; from: string; span: Span }
  | { _tag: "SExpr"; value: Expr; span: Span }
  | { _tag: "SError"; span: Span };
export type Ctor = { name: string; fields: CtorField[]; span: Span };
export type CtorField = { name: Option<string>; fieldType: TypeExpr };
export type AliasField = {
  name: string;
  nameSpan: Span;
  fieldType: TypeExpr;
  optional: boolean;
  spread: boolean;
};
export type Name = { name: string; span: Span };
export type AliasInfo = { params: string[]; fields: AliasField[]; expr: Option<TypeExpr> };
export type Scheme = { vars: number[]; rvars: number[]; ty: Ty };
export type RecoveryQualScope = { types: Set<string>; aliases: Map<string, AliasInfo> };
export type Registry = { ctors: Map<string, CtorInfo>; types: Map<string, string[]> };
export type CtorInfo = { owner: string; arity: number };
export type RecoveryGraphState = { ctx: RecoveryCtx; errors: MErr[] };
export type RecoveryCtx = {
  exportsByPath: Map<string, Map<string, Scheme>>;
  regByPath: Map<string, Registry>;
  keysByPath: Map<string, Map<string, string[]>>;
  qualsByPath: Map<string, RecoveryQualScope>;
  outputs: ModuleOutput[];
};
export type GraphRecovery = { outputs: ModuleOutput[]; errors: MErr[] };
export type Origins = {
  values: Map<string, Loc>;
  types: Map<string, Loc>;
  ctors: Map<string, Loc>;
};
export type Loc = { path: string; start: number; end: number };
export type Occurrence = {
  name: string;
  defStart: number;
  defEnd: number;
  start: number;
  end: number;
  role: string;
};
export type SymPrelude = { origins: Origins; members: Map<string, Loc> };
export type SymIndex = {
  occurrences: SymOccurrence[];
  top: Origins;
  fields: Map<string, Loc>;
  frames: ScopeFrame[];
};
export type SymOccurrence = {
  name: string;
  space: string;
  defPath: string;
  defStart: number;
  defEnd: number;
  start: number;
  end: number;
  role: string;
};
export type ScopeFrame = { start: number; end: number; binds: Map<string, Loc> };
export type Stamped = {
  kind: string;
  message: string;
  start: number;
  end: number;
  help: Option<string>;
  suggestions: Suggestion[];
};
export type SeedModule = {
  buildModulesWith: HostFn<[entry: string, opts: Opts], Result<ModuleOutput[], MErr[]>>;
  buildModulesTsWith: HostFn<
    [entry: string, runtimeImport: string, opts: Opts],
    Result<ModuleOutput[], MErr[]>
  >;
  compileGraphWith: HostFn<[graph: Loaded[], opts: Opts], Result<ModuleOutput[], MErr[]>>;
  inferGraphTypesWith: <A>(
    graph: ({ stmts: Stmt[]; path: string; src: string } & A)[],
    opts: Opts,
  ) => Result<
    {
      path: string;
      types: { span: SpanAt; ty: Ty; display: string; sym: Option<BinderSym> }[];
      aliases: Map<string, AliasInfo>;
      imports: Map<string, Scheme>;
      quals: Map<string, RecoveryQualScope>;
    }[],
    MErr
  >;
  freshInferGraphState: <A, B, C, D, E, F, G, H, I, J, K>() => {
    exportsByPath: Map<A, B>;
    regByPath: Map<C, D>;
    keysByPath: Map<E, F>;
    qualsByPath: Map<G, H>;
    aliases: Map<I, J>;
    outputs: K[];
  };
  inferGraphTypesFromWith: <A>(
    state: {
      exportsByPath: Map<string, Map<string, Scheme>>;
      regByPath: Map<string, Registry>;
      keysByPath: Map<string, Map<string, string[]>>;
      qualsByPath: Map<string, RecoveryQualScope>;
      outputs: {
        path: string;
        types: { span: SpanAt; ty: Ty; display: string; sym: Option<BinderSym> }[];
        aliases: Map<string, AliasInfo>;
        imports: Map<string, Scheme>;
        quals: Map<string, RecoveryQualScope>;
      }[];
      aliases: Map<string, AliasInfo>;
    },
    graph: ({ stmts: Stmt[]; path: string; src: string } & A)[],
    opts: Opts,
  ) => Result<
    {
      exportsByPath: Map<string, Map<string, Scheme>>;
      regByPath: Map<string, Registry>;
      keysByPath: Map<string, Map<string, string[]>>;
      qualsByPath: Map<string, RecoveryQualScope>;
      outputs: {
        path: string;
        types: { span: SpanAt; ty: Ty; display: string; sym: Option<BinderSym> }[];
        aliases: Map<string, AliasInfo>;
        imports: Map<string, Scheme>;
        quals: Map<string, RecoveryQualScope>;
      }[];
      aliases: Map<string, AliasInfo>;
    },
    MErr
  >;
  inferSliceOf: <A, B, C, D, E, F, G, H>(
    state: {
      outputs: ({ path: A } & G)[];
      aliases: B;
      qualsByPath: Map<A, C>;
      keysByPath: Map<A, D>;
      regByPath: Map<A, E>;
      exportsByPath: Map<A, F>;
    } & H,
    path: A,
  ) => {
    exportsByPath: Map<A, F>;
    regByPath: Map<A, E>;
    keysByPath: Map<A, D>;
    qualsByPath: Map<A, C>;
    aliases: B;
    outputs: ({ path: A } & G)[];
  };
  mergeInferStates: <A, B, C, D, E, F, G, H, I, J, K, L, M>(
    a: {
      outputs: A[];
      aliases: Map<B, C>;
      qualsByPath: Map<D, E>;
      keysByPath: Map<F, G>;
      regByPath: Map<H, I>;
      exportsByPath: Map<J, K>;
    } & L,
    b: {
      outputs: A[];
      aliases: Map<B, C>;
      qualsByPath: Map<D, E>;
      keysByPath: Map<F, G>;
      regByPath: Map<H, I>;
      exportsByPath: Map<J, K>;
    } & M,
  ) => {
    exportsByPath: Map<J, K>;
    regByPath: Map<H, I>;
    keysByPath: Map<F, G>;
    qualsByPath: Map<D, E>;
    aliases: Map<B, C>;
    outputs: A[];
  };
  freshRecoveryGraphState: () => RecoveryGraphState;
  recoverModuleWith: HostFn<
    [state: RecoveryGraphState, loaded: Loaded, isEntry: boolean, opts: Opts],
    RecoveryGraphState
  >;
  recoverySliceOf: HostFn<[state: RecoveryGraphState, path: string], RecoveryGraphState>;
  mergeRecoveryStates: HostFn<[a: RecoveryGraphState, b: RecoveryGraphState], RecoveryGraphState>;
  compileGraphRecoveringWith: HostFn<[graph: Loaded[], opts: Opts], GraphRecovery>;
  exportedOrigins: HostFn<[path: string, stmts: Stmt[]], Origins>;
  symbolOccurrences: (stmts: Stmt[]) => Occurrence[];
  symbolIndex: HostFn<
    [path: string, origins: Origins, prelude: SymPrelude, stmts: Stmt[]],
    SymIndex
  >;
  emitDts: HostFn<[src: string, runtimeImport: string], Result<string, Stamped[]>>;
  emitDtsForFileWith: HostFn<
    [entry: string, runtimeImport: string, opts: Opts],
    Result<string, MErr>
  >;
};
