/**
 * The intrinsic JSX element schema — ADR 0096's data, and the SOURCE OF TRUTH
 * for both implementations (ADR 0097).
 *
 * Plain data, no compiler imports: `jsx.ts` reads it directly, and
 * `scripts/gen-jsx-schema.ts` projects it into `bootstrap/plugins/jsx-schema.gen.mjs`
 * for the self-hosted plugin to consume through the host seam, the same way
 * `prelude.gen.mjs` carries the prelude tables (ADR 0075). Adding an attribute
 * is a one-line edit HERE plus `bun run gen:jsx-schema`; neither implementation
 * hand-maintains a second copy.
 *
 * Deliberately NOT exhaustive — the web platform is open-ended, and `data-*`,
 * `aria-*`, and custom elements stay open-world regardless. Add elements and
 * attributes as they are needed.
 */
/** Intrinsic attribute type representation (ADR 0096). */
export type IntrinsicAttrType =
  | "string"
  | "number"
  | "bool"
  | "string|number"
  | "string|bool"
  | "event"
  | "any"
  | readonly string[];

export type ElementSchema = Readonly<Record<string, IntrinsicAttrType>>;

/** Common global HTML attributes allowed on all HTML elements. */
export const GLOBAL_HTML_ATTRS: ElementSchema = {
  id: "string",
  className: "string",
  style: "any",
  title: "string",
  hidden: "bool",
  tabIndex: "number",
  role: "string",
  dir: ["ltr", "rtl", "auto"],
  lang: "string",
  ref: "any",
  key: "string|number",
  slot: "string",
  draggable: "bool",
  spellCheck: "bool",
  contentEditable: "string|bool",
  inputMode: "string",
  accessKey: "string",
  autoCapitalize: "string",
  autoCorrect: "string",
  translate: ["yes", "no"],
  popover: "string|bool",
  popoverTarget: "string",
  popoverTargetAction: ["toggle", "show", "hide"],
  ariaLabel: "string",
  ariaHidden: "string|bool",
  ariaExpanded: "string|bool",
  ariaDisabled: "string|bool",
  ariaChecked: "string|bool",
  ariaSelected: "string|bool",
  ariaInvalid: "string|bool",
  ariaRequired: "string|bool",
  ariaReadOnly: "string|bool",
  ariaValueNow: "number",
  ariaValueMin: "number",
  ariaValueMax: "number",
  ariaValueText: "string",
  ariaLive: ["off", "polite", "assertive"],
  ariaAtomic: "string|bool",
  ariaRelevant: "string",
  ariaBusy: "string|bool",
  ariaControls: "string",
  ariaDescribedBy: "string",
  ariaDetails: "string",
  ariaErrorMessage: "string",
  ariaFlowTo: "string",
  ariaHasPopup: "string|bool",
  ariaKeyShortcuts: "string",
  ariaLabelledBy: "string",
  ariaModal: "string|bool",
  ariaMultiline: "string|bool",
  ariaMultiSelectable: "string|bool",
  ariaOrientation: ["horizontal", "vertical"],
  ariaPlaceholder: "string",
  ariaPressed: "string|bool",
  ariaRoleDescription: "string",
  ariaRowCount: "number",
  ariaRowIndex: "number",
  ariaRowSpan: "number",
  ariaColCount: "number",
  ariaColIndex: "number",
  ariaColSpan: "number",
  ariaSort: ["none", "ascending", "descending", "other"],
  ariaCurrent: "string|bool",
  onClick: "event",
  onDoubleClick: "event",
  onMouseDown: "event",
  onMouseUp: "event",
  onMouseEnter: "event",
  onMouseLeave: "event",
  onMouseMove: "event",
  onMouseOver: "event",
  onMouseOut: "event",
  onContextMenu: "event",
  onAuxClick: "event",
  onKeyDown: "event",
  onKeyUp: "event",
  onKeyPress: "event",
  onInput: "event",
  onChange: "event",
  onFocus: "event",
  onBlur: "event",
  onSubmit: "event",
  onReset: "event",
  onInvalid: "event",
  onScroll: "event",
  onScrollEnd: "event",
  onWheel: "event",
  onTouchStart: "event",
  onTouchMove: "event",
  onTouchEnd: "event",
  onTouchCancel: "event",
  onPointerDown: "event",
  onPointerMove: "event",
  onPointerUp: "event",
  onPointerCancel: "event",
  onPointerEnter: "event",
  onPointerLeave: "event",
  onPointerOver: "event",
  onPointerOut: "event",
  onGotPointerCapture: "event",
  onLostPointerCapture: "event",
  onDrag: "event",
  onDragEnd: "event",
  onDragEnter: "event",
  onDragLeave: "event",
  onDragOver: "event",
  onDragStart: "event",
  onDrop: "event",
  onLoad: "event",
  onError: "event",
  onToggle: "event",
  onClose: "event",
  onCancel: "event",
  onAnimationStart: "event",
  onAnimationEnd: "event",
  onAnimationIteration: "event",
  onTransitionEnd: "event",
  onTransitionRun: "event",
  onTransitionStart: "event",
  onTransitionCancel: "event",
  onSelect: "event",
  onCopy: "event",
  onCut: "event",
  onPaste: "event",
};

/** Common SVG element attributes. */
export const GLOBAL_SVG_ATTRS: ElementSchema = {
  ...GLOBAL_HTML_ATTRS,
  viewBox: "string",
  xmlns: "string",
  fill: "string",
  stroke: "string",
  strokeWidth: "string|number",
  strokeLinecap: ["butt", "round", "square", "inherit"],
  strokeLinejoin: ["miter", "round", "bevel", "inherit"],
  strokeDasharray: "string|number",
  strokeDashoffset: "string|number",
  strokeOpacity: "string|number",
  fillOpacity: "string|number",
  fillRule: ["nonzero", "evenodd", "inherit"],
  opacity: "string|number",
  d: "string",
  x: "string|number",
  y: "string|number",
  cx: "string|number",
  cy: "string|number",
  r: "string|number",
  rx: "string|number",
  ry: "string|number",
  x1: "string|number",
  y1: "string|number",
  x2: "string|number",
  y2: "string|number",
  points: "string",
  width: "string|number",
  height: "string|number",
  transform: "string",
  textAnchor: ["start", "middle", "end", "inherit"],
  dominantBaseline: "string",
  fontSize: "string|number",
  fontFamily: "string",
  fontWeight: "string|number",
  offset: "string|number",
  stopColor: "string",
  stopOpacity: "string|number",
  clipPath: "string",
  mask: "string",
  href: "string",
  xlinkHref: "string",
  preserveAspectRatio: "string",
  gradientUnits: ["userSpaceOnUse", "objectBoundingBox"],
  gradientTransform: "string",
  spreadMethod: ["pad", "reflect", "repeat"],
  patternUnits: ["userSpaceOnUse", "objectBoundingBox"],
  patternContentUnits: ["userSpaceOnUse", "objectBoundingBox"],
  markerWidth: "string|number",
  markerHeight: "string|number",
  refX: "string|number",
  refY: "string|number",
  orient: "string",
};

const makeSchema = (
  base: ElementSchema,
  extra: Readonly<Record<string, IntrinsicAttrType>> = {},
): ElementSchema => ({ ...base, ...extra });

/** Complete dictionary of standard intrinsic HTML and SVG elements. */
export const INTRINSIC_ELEMENTS: Readonly<Record<string, ElementSchema>> = {
  // Container / structural HTML elements
  div: GLOBAL_HTML_ATTRS,
  span: GLOBAL_HTML_ATTRS,
  p: GLOBAL_HTML_ATTRS,
  h1: GLOBAL_HTML_ATTRS,
  h2: GLOBAL_HTML_ATTRS,
  h3: GLOBAL_HTML_ATTRS,
  h4: GLOBAL_HTML_ATTRS,
  h5: GLOBAL_HTML_ATTRS,
  h6: GLOBAL_HTML_ATTRS,
  header: GLOBAL_HTML_ATTRS,
  footer: GLOBAL_HTML_ATTRS,
  nav: GLOBAL_HTML_ATTRS,
  main: GLOBAL_HTML_ATTRS,
  aside: GLOBAL_HTML_ATTRS,
  section: GLOBAL_HTML_ATTRS,
  article: GLOBAL_HTML_ATTRS,
  figure: GLOBAL_HTML_ATTRS,
  figcaption: GLOBAL_HTML_ATTRS,
  mark: GLOBAL_HTML_ATTRS,
  small: GLOBAL_HTML_ATTRS,
  strong: GLOBAL_HTML_ATTRS,
  em: GLOBAL_HTML_ATTRS,
  b: GLOBAL_HTML_ATTRS,
  i: GLOBAL_HTML_ATTRS,
  u: GLOBAL_HTML_ATTRS,
  s: GLOBAL_HTML_ATTRS,
  code: GLOBAL_HTML_ATTRS,
  pre: GLOBAL_HTML_ATTRS,
  kbd: GLOBAL_HTML_ATTRS,
  samp: GLOBAL_HTML_ATTRS,
  var: GLOBAL_HTML_ATTRS,
  sub: GLOBAL_HTML_ATTRS,
  sup: GLOBAL_HTML_ATTRS,
  abbr: GLOBAL_HTML_ATTRS,
  address: GLOBAL_HTML_ATTRS,
  bdi: GLOBAL_HTML_ATTRS,
  bdo: GLOBAL_HTML_ATTRS,
  cite: GLOBAL_HTML_ATTRS,
  dfn: GLOBAL_HTML_ATTRS,
  hr: GLOBAL_HTML_ATTRS,
  br: GLOBAL_HTML_ATTRS,
  wbr: GLOBAL_HTML_ATTRS,
  noscript: GLOBAL_HTML_ATTRS,
  picture: GLOBAL_HTML_ATTRS,
  template: GLOBAL_HTML_ATTRS,
  tbody: GLOBAL_HTML_ATTRS,
  thead: GLOBAL_HTML_ATTRS,
  tfoot: GLOBAL_HTML_ATTRS,
  tr: GLOBAL_HTML_ATTRS,
  caption: GLOBAL_HTML_ATTRS,
  summary: GLOBAL_HTML_ATTRS,
  ul: GLOBAL_HTML_ATTRS,

  // Interactive / specific HTML elements
  button: makeSchema(GLOBAL_HTML_ATTRS, {
    type: ["button", "submit", "reset"],
    disabled: "bool",
    form: "string",
    formAction: "string",
    formMethod: "string",
    formNoValidate: "bool",
    formTarget: "string",
    name: "string",
    value: "string",
    autoFocus: "bool",
  }),
  input: makeSchema(GLOBAL_HTML_ATTRS, {
    type: [
      "text",
      "password",
      "checkbox",
      "radio",
      "number",
      "email",
      "file",
      "hidden",
      "image",
      "range",
      "reset",
      "search",
      "submit",
      "tel",
      "url",
      "date",
      "datetime-local",
      "month",
      "time",
      "week",
      "color",
    ],
    value: "string|number",
    defaultValue: "string|number",
    checked: "bool",
    defaultChecked: "bool",
    placeholder: "string",
    disabled: "bool",
    readOnly: "bool",
    required: "bool",
    name: "string",
    min: "string|number",
    max: "string|number",
    step: "string|number",
    maxLength: "number",
    minLength: "number",
    pattern: "string",
    accept: "string",
    multiple: "bool",
    autoComplete: "string",
    autoFocus: "bool",
    alt: "string",
    src: "string",
    width: "string|number",
    height: "string|number",
    list: "string",
    capture: "string|bool",
    form: "string",
    formAction: "string",
    formMethod: "string",
    formNoValidate: "bool",
    formTarget: "string",
  }),
  a: makeSchema(GLOBAL_HTML_ATTRS, {
    href: "string",
    target: ["_blank", "_self", "_parent", "_top"],
    rel: "string",
    download: "string|bool",
    hrefLang: "string",
    ping: "string",
    referrerPolicy: "string",
    type: "string",
  }),
  img: makeSchema(GLOBAL_HTML_ATTRS, {
    src: "string",
    alt: "string",
    width: "string|number",
    height: "string|number",
    loading: ["lazy", "eager"],
    decoding: ["async", "sync", "auto"],
    crossOrigin: ["anonymous", "use-credentials", ""],
    sizes: "string",
    srcSet: "string",
    useMap: "string",
    isMap: "bool",
    referrerPolicy: "string",
  }),
  form: makeSchema(GLOBAL_HTML_ATTRS, {
    action: "string",
    method: ["get", "post", "dialog"],
    target: "string",
    encType: "string",
    noValidate: "bool",
    autoComplete: "string",
    name: "string",
  }),
  textarea: makeSchema(GLOBAL_HTML_ATTRS, {
    value: "string",
    defaultValue: "string",
    placeholder: "string",
    rows: "number",
    cols: "number",
    disabled: "bool",
    readOnly: "bool",
    required: "bool",
    name: "string",
    maxLength: "number",
    minLength: "number",
    autoFocus: "bool",
    wrap: "string",
    autoComplete: "string",
    form: "string",
  }),
  select: makeSchema(GLOBAL_HTML_ATTRS, {
    value: "string|number",
    defaultValue: "string|number",
    multiple: "bool",
    disabled: "bool",
    required: "bool",
    name: "string",
    size: "number",
    autoFocus: "bool",
    autoComplete: "string",
    form: "string",
  }),
  option: makeSchema(GLOBAL_HTML_ATTRS, {
    value: "string|number",
    disabled: "bool",
    selected: "bool",
    label: "string",
  }),
  optgroup: makeSchema(GLOBAL_HTML_ATTRS, {
    disabled: "bool",
    label: "string",
  }),
  label: makeSchema(GLOBAL_HTML_ATTRS, {
    htmlFor: "string",
    form: "string",
  }),
  canvas: makeSchema(GLOBAL_HTML_ATTRS, {
    width: "string|number",
    height: "string|number",
  }),
  dialog: makeSchema(GLOBAL_HTML_ATTRS, {
    open: "bool",
  }),
  details: makeSchema(GLOBAL_HTML_ATTRS, {
    open: "bool",
  }),
  audio: makeSchema(GLOBAL_HTML_ATTRS, {
    src: "string",
    autoPlay: "bool",
    controls: "bool",
    loop: "bool",
    muted: "bool",
    preload: ["none", "metadata", "auto", ""],
    crossOrigin: "string",
  }),
  video: makeSchema(GLOBAL_HTML_ATTRS, {
    src: "string",
    autoPlay: "bool",
    controls: "bool",
    loop: "bool",
    muted: "bool",
    preload: ["none", "metadata", "auto", ""],
    width: "string|number",
    height: "string|number",
    poster: "string",
    playsInline: "bool",
    crossOrigin: "string",
    disablePictureInPicture: "bool",
    disableRemotePlayback: "bool",
  }),
  source: makeSchema(GLOBAL_HTML_ATTRS, {
    src: "string",
    type: "string",
    srcSet: "string",
    sizes: "string",
    media: "string",
    width: "string|number",
    height: "string|number",
  }),
  track: makeSchema(GLOBAL_HTML_ATTRS, {
    kind: ["subtitles", "captions", "descriptions", "chapters", "metadata"],
    src: "string",
    srclang: "string",
    label: "string",
    default: "bool",
  }),
  iframe: makeSchema(GLOBAL_HTML_ATTRS, {
    src: "string",
    srcDoc: "string",
    name: "string",
    width: "string|number",
    height: "string|number",
    loading: ["lazy", "eager"],
    sandbox: "string",
    allow: "string",
    allowFullScreen: "bool",
    referrerPolicy: "string",
  }),
  table: makeSchema(GLOBAL_HTML_ATTRS, {
    cellPadding: "string|number",
    cellSpacing: "string|number",
  }),
  th: makeSchema(GLOBAL_HTML_ATTRS, {
    colSpan: "number",
    rowSpan: "number",
    scope: "string",
    headers: "string",
  }),
  td: makeSchema(GLOBAL_HTML_ATTRS, {
    colSpan: "number",
    rowSpan: "number",
    headers: "string",
  }),
  col: makeSchema(GLOBAL_HTML_ATTRS, {
    span: "number",
  }),
  colgroup: makeSchema(GLOBAL_HTML_ATTRS, {
    span: "number",
  }),
  ol: makeSchema(GLOBAL_HTML_ATTRS, {
    start: "number",
    reversed: "bool",
    type: "string",
  }),
  li: makeSchema(GLOBAL_HTML_ATTRS, {
    value: "number",
  }),
  meta: makeSchema(GLOBAL_HTML_ATTRS, {
    name: "string",
    content: "string",
    httpEquiv: "string",
    charSet: "string",
    property: "string",
  }),
  link: makeSchema(GLOBAL_HTML_ATTRS, {
    href: "string",
    rel: "string",
    as: "string",
    type: "string",
    crossOrigin: "string",
    media: "string",
    sizes: "string",
    hrefLang: "string",
    referrerPolicy: "string",
    integrity: "string",
  }),
  script: makeSchema(GLOBAL_HTML_ATTRS, {
    src: "string",
    type: "string",
    async: "bool",
    defer: "bool",
    crossOrigin: "string",
    integrity: "string",
    noModule: "bool",
    referrerPolicy: "string",
  }),
  style: makeSchema(GLOBAL_HTML_ATTRS, {
    media: "string",
    nonce: "string",
  }),
  progress: makeSchema(GLOBAL_HTML_ATTRS, {
    value: "string|number",
    max: "string|number",
  }),
  meter: makeSchema(GLOBAL_HTML_ATTRS, {
    value: "string|number",
    min: "string|number",
    max: "string|number",
    low: "string|number",
    high: "string|number",
    optimum: "string|number",
    form: "string",
  }),
  time: makeSchema(GLOBAL_HTML_ATTRS, {
    dateTime: "string",
  }),
  blockquote: makeSchema(GLOBAL_HTML_ATTRS, {
    cite: "string",
  }),
  q: makeSchema(GLOBAL_HTML_ATTRS, {
    cite: "string",
  }),
  del: makeSchema(GLOBAL_HTML_ATTRS, {
    cite: "string",
    dateTime: "string",
  }),
  ins: makeSchema(GLOBAL_HTML_ATTRS, {
    cite: "string",
    dateTime: "string",
  }),

  // SVG elements
  svg: GLOBAL_SVG_ATTRS,
  g: GLOBAL_SVG_ATTRS,
  path: GLOBAL_SVG_ATTRS,
  circle: GLOBAL_SVG_ATTRS,
  rect: GLOBAL_SVG_ATTRS,
  line: GLOBAL_SVG_ATTRS,
  polyline: GLOBAL_SVG_ATTRS,
  polygon: GLOBAL_SVG_ATTRS,
  text: GLOBAL_SVG_ATTRS,
  tspan: GLOBAL_SVG_ATTRS,
  use: GLOBAL_SVG_ATTRS,
  symbol: GLOBAL_SVG_ATTRS,
  defs: GLOBAL_SVG_ATTRS,
  clipPath: GLOBAL_SVG_ATTRS,
  mask: GLOBAL_SVG_ATTRS,
  pattern: GLOBAL_SVG_ATTRS,
  linearGradient: GLOBAL_SVG_ATTRS,
  radialGradient: GLOBAL_SVG_ATTRS,
  stop: GLOBAL_SVG_ATTRS,
  image: GLOBAL_SVG_ATTRS,
  foreignObject: GLOBAL_SVG_ATTRS,
  marker: GLOBAL_SVG_ATTRS,
};

/** Common JSX migration and spelling mistake hints. */
export const JSX_MISMATCH_HINTS: Readonly<Record<string, string>> = {
  class: "In JSX, use 'className' instead of 'class'.",
  for: "In JSX, use 'htmlFor' instead of 'for'.",
  tabindex: "In JSX, use 'tabIndex' instead of 'tabindex'.",
  autofocus: "In JSX, use 'autoFocus' instead of 'autofocus'.",
  autocomplete: "In JSX, use 'autoComplete' instead of 'autocomplete'.",
  readonly: "In JSX, use 'readOnly' instead of 'readonly'.",
  maxlength: "In JSX, use 'maxLength' instead of 'maxlength'.",
  minlength: "In JSX, use 'minLength' instead of 'minlength'.",
  spellcheck: "In JSX, use 'spellCheck' instead of 'spellcheck'.",
  contenteditable: "In JSX, use 'contentEditable' instead of 'contenteditable'.",
  viewbox: "In JSX, use 'viewBox' instead of 'viewbox'.",
  strokewidth: "In JSX, use 'strokeWidth' instead of 'strokewidth'.",
  strokelinecap: "In JSX, use 'strokeLinecap' instead of 'strokelinecap'.",
  strokelinejoin: "In JSX, use 'strokeLinejoin' instead of 'strokelinejoin'.",
  onclick: "In JSX, event handlers are camelCase: use 'onClick' instead of 'onclick'.",
  onchange: "In JSX, event handlers are camelCase: use 'onChange' instead of 'onchange'.",
  oninput: "In JSX, event handlers are camelCase: use 'onInput' instead of 'oninput'.",
  onkeydown: "In JSX, event handlers are camelCase: use 'onKeyDown' instead of 'onkeydown'.",
  onkeyup: "In JSX, event handlers are camelCase: use 'onKeyUp' instead of 'onkeyup'.",
  onsubmit: "In JSX, event handlers are camelCase: use 'onSubmit' instead of 'onsubmit'.",
  onfocus: "In JSX, event handlers are camelCase: use 'onFocus' instead of 'onfocus'.",
  onblur: "In JSX, event handlers are camelCase: use 'onBlur' instead of 'onblur'.",
};
