// Self-contained type declarations for hosts of the frozen seed (ADR 0109).
//
// Host plugins need the seed's AST and type aliases, but importing the emitted
// `.ts` pulls the whole seed into the host's program, and the seed is only
// strict-clean under plain `--strict` (not `noUncheckedIndexedAccess`). This
// copies just the requested aliases, plus every alias they reference, into one
// `.d.ts`, which `skipLibCheck` leaves alone.
import { readFileSync } from "node:fs";
import { join } from "node:path";

export type HostTypeRoot = { file: string; names: readonly string[] };

type SeedFile = { aliases: Map<string, string>; imports: Map<string, string> };

const RUNTIME_TYPES = ["Option", "Result", "_Curry"] as const;

/** End index (exclusive) of the alias starting at `from`: its `;` at depth 0. */
const aliasEnd = (src: string, from: number): number => {
  let depth = 0;
  for (let i = from; i < src.length; i++) {
    const c = src[i]!;
    if (c === '"' || c === "'" || c === "`") {
      i = src.indexOf(c, i + 1);
      continue;
    }
    if (c === "{" || c === "(" || c === "[" || c === "<") depth++;
    else if (c === "}" || c === ")" || c === "]") depth--;
    else if (c === ">" && src[i - 1] !== "=") depth--;
    else if (c === ";" && depth === 0) return i + 1;
  }
  throw new Error(`unterminated type alias at ${from}`);
};

const readSeedFile = (dir: string, file: string): SeedFile => {
  const src = readFileSync(join(dir, file), "utf8");
  const aliases = new Map<string, string>();
  for (const m of src.matchAll(/^export type ([A-Za-z_$][\w$]*)\b/gm)) {
    aliases.set(m[1]!, src.slice(m.index, aliasEnd(src, m.index + m[0].length)));
  }
  const imports = new Map<string, string>();
  for (const m of src.matchAll(/^import type \{([^}]*)\} from "\.\/([\w/-]+)";?$/gm)) {
    for (const name of m[1]!
      .split(",")
      .map((n) => n.trim())
      .filter(Boolean))
      imports.set(name, `${m[2]}.ts`);
  }
  return { aliases, imports };
};

const words = (text: string): Set<string> => new Set(text.match(/[A-Za-z_$][\w$]*/g) ?? []);

/** The `.d.ts` text: each root alias and its closure, in discovery order. */
export const hostTypesDts = (seedDir: string, roots: readonly HostTypeRoot[]): string => {
  const files = new Map<string, SeedFile>();
  const fileOf = (file: string): SeedFile => {
    const cached = files.get(file);
    if (cached) return cached;
    const loaded = readSeedFile(seedDir, file);
    files.set(file, loaded);
    return loaded;
  };
  const owner = new Map<string, string>();
  const out: string[] = [];
  const visit = (name: string, file: string): void => {
    const seen = owner.get(name);
    if (seen === file) return;
    if (seen !== undefined)
      throw new Error(`host type '${name}' is declared in both ${seen} and ${file}`);
    const decl = fileOf(file).aliases.get(name);
    if (decl === undefined) throw new Error(`${file} declares no type alias '${name}'`);
    owner.set(name, file);
    out.push(decl);
    for (const ref of words(decl.slice(decl.indexOf("=")))) {
      if (ref === name) continue;
      if (fileOf(file).aliases.has(ref)) visit(ref, file);
      else {
        const from = fileOf(file).imports.get(ref);
        if (from !== undefined) visit(ref, from);
      }
    }
  };
  for (const { file, names } of roots) for (const name of names) visit(name, file);
  const body = out.join("\n");
  const used = RUNTIME_TYPES.filter((t) => words(body).has(t));
  const header =
    used.length > 0 ? `import type { ${used.join(", ")} } from "@mochi/compiler/runtime";\n` : "";
  return `// Generated by scripts/freeze-seed.ts — do not edit.\n${header}${body}\n`;
};
