// Generate `packages/compiler/src/prelude/js-defs.gen.ts` — the JS-backend view
// of the runtime (ADR 0075). The SOURCE OF TRUTH is the typed TS runtime
// `packages/compiler/src/prelude/runtime.ts`: ordinary TypeScript that `tsc
// --strict` checks and biome formats. This script strips its types and records
// what codegen needs — the def text keyed by name, and the reference graph that
// lets codegen inline only the defs a program actually reaches.
//
// Regenerate with `bun run gen:prelude-defs`; `--check` verifies the checked-in
// file matches (also guarded by `test/prelude-defs.spec.ts`).
//
// Type stripping is `Bun.Transpiler`, so the emitted text is Bun's printer
// output rather than the hand-spacing of the source. That is deterministic for a
// given Bun version; a Bun upgrade that re-prints differently shows up as a
// `--check` failure and is fixed by regenerating.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const RUNTIME_PATH = "packages/compiler/src/prelude/runtime.ts";
export const DEFS_PATH = "packages/compiler/src/prelude/js-defs.gen.ts";

const ROOT = join(import.meta.dir, "..");

/** `export const name = …` at column 0 opens a statement; its body lines are indented. */
const DECL_HEAD = /^export const (\w+) = /;

type Def = { readonly name: string; readonly js: string };

/**
 * Split the transpiled runtime into one entry per top-level definition, in
 * SOURCE ORDER — the emitted preamble is evaluated top to bottom, so a def that
 * runs `_curry(2, …)` at definition time has to come after `_curry`.
 */
const splitDefs = (js: string): Def[] => {
  const lines = js.split("\n");
  const heads = lines.flatMap((line, i) => {
    const m = line.match(DECL_HEAD);
    return m ? [{ name: m[1] as string, at: i }] : [];
  });
  return heads.map((head, k) => {
    const end = k + 1 < heads.length ? (heads[k + 1] as { at: number }).at : lines.length;
    const text = lines.slice(head.at, end).join("\n").trim();
    return { name: head.name, js: text.replace(/^export /, "") };
  });
};

/**
 * Identifiers a def body actually references. Strings, comments and property
 * names are skipped, so `r._tag === "Ok"` reports `Ok` only when `Ok` is called
 * — the difference between a real dependency and a coincidence of spelling.
 */
const identifiers = (src: string): Set<string> => {
  const out = new Set<string>();
  let i = 0;
  let prev = "";
  while (i < src.length) {
    const ch = src[i] as string;
    const two = src.slice(i, i + 2);
    if (two === "//") {
      i = src.indexOf("\n", i);
      if (i === -1) break;
      continue;
    }
    if (two === "/*") {
      const end = src.indexOf("*/", i + 2);
      i = end === -1 ? src.length : end + 2;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      i += 1;
      while (i < src.length && src[i] !== ch) i += src[i] === "\\" ? 2 : 1;
      i += 1;
      prev = ch;
      continue;
    }
    if (/[A-Za-z_$]/.test(ch)) {
      let j = i;
      while (j < src.length && /[A-Za-z0-9_$]/.test(src[j] as string)) j += 1;
      // `x.map` is a method on x, not the prelude's `map`.
      if (prev !== ".") out.add(src.slice(i, j));
      prev = "id";
      i = j;
      continue;
    }
    if (!/\s/.test(ch)) prev = ch;
    i += 1;
  }
  return out;
};

/** Def name → the other defs its body reaches, in declaration order. */
const depsOf = (defs: readonly Def[]): Record<string, string[]> => {
  const names = new Set(defs.map((d) => d.name));
  const out: Record<string, string[]> = {};
  for (const { name, js } of defs) {
    // Drop the `const NAME = ` head so a def never depends on itself by its own
    // binder; a recursive body (`eq`, `show`) still resolves through the RHS.
    const body = js.replace(DECL_HEAD, "").replace(/^const \w+ = /, "");
    const deps = defs
      .map((d) => d.name)
      .filter((dep) => dep !== name && names.has(dep) && identifiers(body).has(dep));
    if (deps.length > 0) out[name] = deps;
  }
  return out;
};

const quote = (s: string): string => JSON.stringify(s);

export const buildDefsSource = (): string => {
  const ts = readFileSync(join(ROOT, RUNTIME_PATH), "utf8");
  const defs = splitDefs(new Bun.Transpiler({ loader: "ts" }).transformSync(ts));
  const deps = depsOf(defs);
  const header = [
    "// GENERATED by scripts/gen-prelude-defs.ts — do not edit.",
    "// Regenerate with `bun run gen:prelude-defs`; guarded by test/prelude-defs.spec.ts.",
    "//",
    "// The typed runtime `runtime.ts` is the source of truth (ADR 0075); this is that",
    "// module with its types stripped, keyed by name so codegen inlines only what a",
    "// program references, plus the reference graph that closes over those picks.",
    "",
  ].join("\n");
  const defsBody = defs.map((d) => `  ${d.name}: ${quote(d.js)},`).join("\n");
  const depsBody = Object.entries(deps)
    .map(([name, ds]) => `  ${name}: [${ds.map(quote).join(", ")}],`)
    .join("\n");
  return [
    header,
    "/** Runtime definition text, in evaluation order. */",
    "export const preludeJsDefs: Record<string, string> = {",
    defsBody,
    "};",
    "",
    "/** Runtime-dependency graph: def name → other defs its body references. */",
    "export const runtimeDeps: Record<string, string[]> = {",
    depsBody,
    "};",
    "",
  ].join("\n");
};

if (import.meta.main) {
  const source = buildDefsSource();
  const path = join(ROOT, DEFS_PATH);
  if (process.argv.includes("--check")) {
    const onDisk = readFileSync(path, "utf8");
    if (onDisk !== source) {
      console.error(`${DEFS_PATH} is stale — run \`bun run gen:prelude-defs\``);
      process.exit(1);
    }
    console.error(`${DEFS_PATH} is up to date`);
  } else {
    writeFileSync(path, source);
    console.error(`wrote ${DEFS_PATH}`);
  }
}
