// Generate a TypeScript declaration sidecar beside every `.mochi` module in a
// target tree, so host `.ts`/`.tsx` files resolve `.mochi` imports with real
// per-module types instead of a hand-maintained `declare module "*.mochi"`
// wildcard. `X.mochi` → `X.d.mochi.ts` is the TS 5 `allowArbitraryExtensions`
// convention (`{basename}.d.{ext}.ts`) — not `X.mochi.d.ts` (that would declare
// `X.mochi.js`) and not bare `X.d.ts` (that would declare `X.ts`/`X.tsx`).
// Sidecars are gitignored; docs `check`/`dev`/`build` regenerate them.
//
// Default: write each sidecar. `--check`: exit non-zero on drift (local
// idempotency probe — not part of the QA gate once files are gitignored).
//
// Docs tree registers the docs project's vendor-plugin list (#20, ADR 0010)
// so `tw.*` factories emit `$tone` unions — not part of language core.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { emitDts } from "@mochi/compiler/dts";
import { isErr, unwrapOk } from "@onrails/result";
import { docsVendorPlugins } from "../apps/docs/mochi.plugins";
import { snakeVendorPlugins } from "../examples/snake/mochi.plugins";

const root = join(import.meta.dir, "..");
const args = process.argv.slice(2);
const check = args.includes("--check");
const roots = args.filter((a) => !a.startsWith("--"));
const targets = (roots.length ? roots : ["apps/docs/src"]).map((t) =>
  t.startsWith("/") ? t : join(root, t),
);

const sidecarPath = (file: string): string => `${file.slice(0, -".mochi".length)}.d.mochi.ts`;

// The Vite plugin gives every module a default export (its last binding), so the
// sidecar mirrors that — `import FeatureCard from "./FeatureCard.mochi"` resolves.
const withDefaultExport = (decls: string): string => {
  const names = [...decls.matchAll(/^export declare const (\w+):/gm)].map((m) => m[1] as string);
  const last = names.at(-1);
  return last
    ? `${decls}declare const _default: typeof ${last};\nexport default _default;\n`
    : decls;
};

const header = "// Generated by scripts/gen-mochi-dts.ts — do not edit.\n";

// `VNode` is jsx-plugin vocabulary with no declaration anywhere (ADR 0011); a
// sidecar that names it (e.g. an annotated `type Props = { body: VNode }`,
// ADR 0055) would otherwise reference a dangling type. These trees render with
// Preact, so pin it to the real thing — host tooling may name the host.
const withVNodeAlias = (decls: string): string =>
  /\bVNode\b/.test(decls) ? `type VNode = import("preact").VNode;\n${decls}` : decls;

/** Vendor plugins per app tree (`apps/docs/mochi.plugins.ts`, `examples/snake/mochi.plugins.ts`). Other roots stay core-only. */
const pluginsFor = (dir: string) => {
  if (dir.includes(join("apps", "docs")) || dir.endsWith("apps/docs/src")) return docsVendorPlugins;
  if (dir.includes(join("examples", "snake")) || dir.endsWith("examples/snake/src"))
    return snakeVendorPlugins;
  return [];
};

const files = targets
  .flatMap((dir) => [...new Bun.Glob("**/*.mochi").scanSync({ cwd: dir })].map((f) => join(dir, f)))
  .toSorted();

const drift: string[] = [];
for (const file of files) {
  const targetRoot = targets.find((t) => file.startsWith(t)) ?? targets[0]!;
  const r = emitDts(readFileSync(file, "utf8"), { plugins: pluginsFor(targetRoot) });
  if (isErr(r)) {
    for (const d of r.error) console.error(`dts error in ${file}: ${d.kind}: ${d.message}`);
    process.exit(1);
  }
  const out = `${header}${withVNodeAlias(withDefaultExport(unwrapOk(r)))}`;
  const path = sidecarPath(file);
  const current = Bun.file(path).size ? readFileSync(path, "utf8") : null;
  if (current === out) continue;
  if (check) drift.push(path);
  else {
    writeFileSync(path, out);
    console.error(`  generated ${path}`);
  }
}

if (check && drift.length) {
  console.error(
    `stale .mochi declarations (run \`bun run gen:mochi-dts\`):\n${drift.map((f) => `  ${f}`).join("\n")}`,
  );
  process.exit(1);
}
