// Generate `bootstrap/plugins/jsx-schema.gen.mjs` — the self-hosted plugin's view
// of the intrinsic JSX element schema (ADR 0097). The SOURCE OF TRUTH is
// `packages/compiler/src/extensions/plugins/jsx-schema.ts`, which `jsx.ts` and
// `@mochi/dx` read directly.
//
// The self-host reaches it through the host seam rather than as a compiled
// module, exactly as `prelude.gen.mjs` carries the prelude tables (ADR 0075):
// the schema is data the plugin looks things up in, never something it pattern
// matches over, so keeping it out of the graph costs nothing and keeps the
// reviewed `bootstrap/seed/` snapshot from carrying 600 lines of table.
//
// Attribute kinds cross the seam as strings. An enum-valued attribute becomes
// `enum:a,b,c`, which `jsx.mochi` splits — one flat `Map<string, string>` per
// element beats mirroring a variant type across the boundary.
//
// Regenerate with `bun run gen:jsx-schema`; `--check` verifies the checked-in
// file matches (also guarded by `test/jsx-schema.spec.ts`).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  type ElementSchema,
  INTRINSIC_ELEMENTS,
  type IntrinsicAttrType,
  JSX_MISMATCH_HINTS,
} from "../packages/compiler/src/extensions/plugins/jsx-schema";

export const SCHEMA_PATH = "packages/compiler/src/extensions/plugins/jsx-schema.ts";
export const GEN_PATH = "bootstrap/plugins/jsx-schema.gen.mjs";

const ROOT = join(import.meta.dir, "..");

/** One attribute's kind as the seam spells it. */
const kindOf = (attr: IntrinsicAttrType): string =>
  typeof attr === "string" ? attr : `enum:${attr.join(",")}`;

/** `new Map([[k, v], …])`, keys sorted so the output is stable across runs. */
const mapLiteral = (entries: readonly (readonly [string, string])[], indent: string): string => {
  const body = [...entries]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([k, v]) => `${indent}  [${JSON.stringify(k)}, ${JSON.stringify(v)}],`)
    .join("\n");
  return `new Map([\n${body}\n${indent}])`;
};

/**
 * Most tags share one attribute table by reference (`div`, `span`, … are all
 * `GLOBAL_HTML_ATTRS`), so emit each DISTINCT table once as a const and let the
 * tag map reference it. Without this the file is ~15k lines of repeated globals
 * instead of a reviewable artifact.
 */
const tableConsts = (): { readonly decls: string; readonly nameOf: Map<string, string> } => {
  const nameOf = new Map<string, string>(); // serialized table -> const name
  const decls: string[] = [];
  for (const schema of Object.values(INTRINSIC_ELEMENTS)) {
    const attrs = Object.entries(schema).map(([name, t]) => [name, kindOf(t)] as const);
    const key = JSON.stringify([...attrs].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
    if (nameOf.has(key)) continue;
    const name = `_t${nameOf.size}`;
    nameOf.set(key, name);
    decls.push(`const ${name} = ${mapLiteral(attrs, "")};`);
  }
  return { decls: decls.join("\n\n"), nameOf };
};

const tableKey = (schema: ElementSchema): string =>
  JSON.stringify(
    Object.entries(schema)
      .map(([name, t]) => [name, kindOf(t)] as const)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  );

export const buildSchemaSource = (): string => {
  const { decls, nameOf } = tableConsts();
  const elements = Object.entries(INTRINSIC_ELEMENTS)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([tag, schema]) => `  [${JSON.stringify(tag)}, ${nameOf.get(tableKey(schema))}],`)
    .join("\n");
  const hints = mapLiteral(Object.entries(JSX_MISMATCH_HINTS), "");
  return [
    "// GENERATED by `bun run gen:jsx-schema` — do not edit.",
    `// Source of truth: ${SCHEMA_PATH} (ADR 0096 data, ADR 0097 seam).`,
    "//",
    "// `intrinsicElements`: tag -> (attribute -> kind), where kind is one of",
    '// "string" | "number" | "bool" | "string|number" | "string|bool" | "event"',
    '// | "any" | "enum:a,b,c". Tags sharing an attribute table share its const.',
    "",
    decls,
    "",
    "export const intrinsicElements = new Map([",
    elements,
    "]);",
    "",
    "/** Attribute spellings that are a known JSX migration trap, with their advice. */",
    `export const jsxMismatchHints = ${hints};`,
    "",
  ].join("\n");
};

if (import.meta.main) {
  const source = buildSchemaSource();
  const path = join(ROOT, GEN_PATH);
  if (process.argv.includes("--check")) {
    const onDisk = readFileSync(path, "utf8");
    if (onDisk !== source) {
      console.error(`${GEN_PATH} is stale — run \`bun run gen:jsx-schema\``);
      process.exit(1);
    }
    console.error(`${GEN_PATH} is up to date`);
  } else {
    writeFileSync(path, source);
    console.error(`wrote ${GEN_PATH}`);
  }
}
