// Generator for `bootstrap/prelude.gen.mjs` — the standalone prelude-table shim
// the shipped self-hosted compiler imports (ticket 0004). The five tables live
// once in `src/prelude.ts`; the shipped `mochic` cannot import from `src/`, so
// this script lowers them into a plain ESM data module.
//
// Drift control (PATH_TO_BOOTSTRAP §6 — one prelude, never forked): the shim is
// GENERATED, never hand-edited. `test/prelude-shim.spec.ts` regenerates in
// memory and asserts byte-equality with the checked-in file, so any edit to
// `src/prelude.ts` (or to infer.mochi's `Ty` runtime shape) that skips
// `bun run gen:prelude` fails CI.
//
// The two inference tables (`preludeEnv`, `preludeNamespaces`) hold TS `Type`
// values; they are lowered to mochi's `Ty` runtime representation using
// infer.mochi's OWN constructors (compiled + evaluated here, exactly as the
// differential test does) so the embedded data can never drift from the shape
// the bootstrap inferrer expects.
import { match } from "@onrails/pattern";
import { unwrapOk } from "@onrails/result";
import { compile } from "../src/compile";
import {
  namespaceRuntime,
  preludeEnv,
  preludeJsDefs,
  preludeNamespaces,
  runtimeDeps,
} from "../src/prelude";
import type { Row, Type } from "../src/types";

export const SHIM_PATH = "bootstrap/prelude.gen.mjs";

// --- load infer.mochi's Ty/Row constructors from the compiled module ---
type AlInfer = {
  tVar: (id: number) => unknown;
  tCon: (name: string, args: unknown[]) => unknown;
  tArrow: (from: unknown, to: unknown) => unknown;
  tRecord: (row: unknown) => unknown;
  rVar: (id: number) => unknown;
  rExtend: (label: string, fieldType: unknown, rest: unknown) => unknown;
  RowEmpty: unknown;
};

const evalAlNames = <T extends Record<string, unknown>>(js: string, names: string[]): T =>
  new Function(
    "match",
    `"use strict";\n${js.replace(/^import .*$/gm, "").replace(/^export /gm, "")}\nreturn { ${names.join(", ")} };`,
  )(match) as T;

// --- TS Type/Row -> mochi Ty/Row runtime value (mirrors bootstrap-infer.spec) ---
const makeConverters = (al: AlInfer) => {
  const tsTypeToAl = (t: Type): unknown => {
    switch (t.kind) {
      case "var":
        return al.tVar(t.id);
      case "con":
        return al.tCon(
          t.name,
          t.args.map((a) => tsTypeToAl(a)),
        );
      case "arrow":
        return al.tArrow(tsTypeToAl(t.from), tsTypeToAl(t.to));
      case "record":
        return al.tRecord(tsRowToAl(t.row));
    }
  };
  const tsRowToAl = (r: Row): unknown => {
    switch (r.kind) {
      case "empty":
        return al.RowEmpty;
      case "rvar":
        return al.rVar(r.id);
      case "extend":
        return al.rExtend(r.label, tsTypeToAl(r.type), tsRowToAl(r.rest));
    }
  };
  return { tsTypeToAl };
};

// Build the shim's ESM source. Pure function of src/prelude.ts + infer.mochi, so
// the parity test can call it and compare against the checked-in file.
export const buildShimSource = (): string => {
  const alInfer = evalAlNames<AlInfer>(unwrapOk(compile(readTypes())), [
    "tVar",
    "tCon",
    "tArrow",
    "tRecord",
    "rVar",
    "rExtend",
    "RowEmpty",
  ]);
  const { tsTypeToAl } = makeConverters(alInfer);

  // Inference tables lowered to mochi Ty (plain tagged records -> JSON-safe).
  const builtins: Record<string, unknown> = {};
  for (const [name, t] of Object.entries(preludeEnv)) builtins[name] = tsTypeToAl(t);

  const namespaces: Record<string, Record<string, unknown>> = {};
  for (const [ns, members] of Object.entries(preludeNamespaces)) {
    const m: Record<string, unknown> = {};
    for (const [name, t] of Object.entries(members)) m[name] = tsTypeToAl(t);
    namespaces[ns] = m;
  }

  const j = (v: unknown): string => JSON.stringify(v, null, 2);
  return `// GENERATED by scripts/gen-prelude.ts — DO NOT EDIT.
// Regenerate with \`bun run gen:prelude\`. Guarded by test/prelude-shim.spec.ts.
// The standalone prelude-table shim for the self-hosted compiler (ticket 0004).
const _builtins = ${j(builtins)};
const _namespaces = ${j(namespaces)};
const _namespaceRuntime = ${j(namespaceRuntime)};
const _preludeJsDefs = ${j(preludeJsDefs)};
const _runtimeDeps = ${j(runtimeDeps)};

const _map = (o) => new Map(Object.entries(o));
const _mapmap = (o) => new Map(Object.entries(o).map(([k, v]) => [k, _map(v)]));

// name -> Ty  (for the inferrer's builtin environment)
export const builtins = _map(_builtins);
// namespace -> (member -> Ty)  (for namespaced builtins, e.g. Array.map)
export const namespaces = _mapmap(_namespaces);
// namespace -> (member -> emitted JS)  (codegen)
export const namespaceRuntime = _mapmap(_namespaceRuntime);
// name -> emitted JS runtime definition  (codegen)
export const preludeJsDefs = _map(_preludeJsDefs);
// name -> [dependency names]  (codegen runtime-dependency graph)
export const runtimeDeps = _map(_runtimeDeps);
`;
};

// types.mochi source read lazily. Ty/Row and their constructors live here (split
// out of infer.mochi, ticket 0013); it's self-contained (no AST import) so it
// still compiles single-file open-world, unlike infer.mochi.
const readTypes = (): string => {
  const { readFileSync } = require("node:fs");
  const { join } = require("node:path");
  return readFileSync(join(import.meta.dir, "..", "bootstrap/types.mochi"), "utf8");
};

// Run directly: (re)write the checked-in shim.
if (import.meta.main) {
  const { join } = await import("node:path");
  const out = join(import.meta.dir, "..", SHIM_PATH);
  await Bun.write(out, buildShimSource());
  console.error(`  wrote ${SHIM_PATH}`);
}
