// TypeScript backend — AST → typed `.ts` source (ADR 0026; Axis A of
// docs/TS_DIALECT.md). Not a fresh emitter: it orchestrates the two backends we
// already have. Types come from `dts.ts` (the `.d.ts` writer's HM-type → TS-type
// machinery, reused inline); values come from `codegen.ts` via its `annotate`
// and `annotateCtor` hooks, which splice each binding's / ctor factory's type in.
//
// Runtime helpers (`_curry`, `add`, …) are imported from the typed runtime module
// (`src/runtime.ts`, generated by scripts/gen-runtime.ts) instead of inlined — so
// the emitted `.ts` is strict-`tsc`-clean end to end. The import specifier is
// configurable (`runtimeImport`), defaulting to the published package name.
import { flatMap, isErr, map, ok, pipe, type Result } from "@onrails/result";
import type { Expr } from "./ast";
import { check } from "./check";
import { codegen, collectRuntimeDeps } from "./codegen";
import {
  aliasTsDecl,
  bindingTsType,
  ctorFactoryTs,
  referencedBuiltinTypeDecls,
  typeDecl,
} from "./dts";
import type { AlangError } from "./errors";
import { inferProgramTypes } from "./infer";
import { lex } from "./lexer";
import { parse } from "./parser";
import { preludeEnv, preludeNamespaces } from "./prelude";

export type CodegenTsOptions = { runtimeImport?: string };

const DEFAULT_RUNTIME_IMPORT = "@alang/runtime";

// Runtime names the typed runtime module exports (everything except the builtin
// ctors, which the emitted module names via its own `export type` header + the
// runtime's factory exports). Imported, never inlined.
export const codegenTs = (src: string, opts: CodegenTsOptions = {}): Result<string, AlangError> => {
  const r = pipe(
    lex(src),
    flatMap(parse),
    flatMap(check),
    flatMap((prog) =>
      map(
        inferProgramTypes(prog, preludeEnv, { open: true, namespaces: preludeNamespaces }),
        (res) => ({
          prog,
          env: res.env,
          aliases: res.aliases,
        }),
      ),
    ),
  );
  if (isErr(r)) return r;
  const { prog, env, aliases } = r.value;
  const aliasByName = new Map(aliases.map((a) => [a.name, a]));

  // Header: builtin unions referenced by the API (`Option<number>`, …) then each
  // `type` decl as an `export type`. Sits alongside codegen's typed ctor
  // factories — TS keeps type and value namespaces separate, so no clash.
  const typeHeader = [
    ...referencedBuiltinTypeDecls(prog, (n) => env.get(n)),
    ...prog.stmts.flatMap((s) => {
      if (s.kind !== "type") return [];
      const a = aliasByName.get(s.name);
      return [a ? aliasTsDecl(a) : typeDecl(s.name, s.params, s.ctors)];
    }),
  ];

  // Runtime import: the builtins the program uses, pulled from the typed module.
  const deps = collectRuntimeDeps(prog);
  const runtimeLine = deps.length
    ? `import { ${deps.join(", ")} } from ${JSON.stringify(opts.runtimeImport ?? DEFAULT_RUNTIME_IMPORT)};`
    : "";

  // Annotate function-valued top-level lets. Lambda params are where TS inference
  // is weakest (bare `(x) => …` infers `any` under strict) and where the
  // generic/nominal signature pays off. A non-function polymorphic binding has no
  // place to bind generics — dts renders its escaped vars as `unknown` — so
  // annotating it would be worse than TS's own inference; skip it.
  const annotate = (name: string, value: Expr): string | null => {
    if (value.kind !== "lambda" || name.startsWith("$")) return null;
    const sc = env.get(name);
    return sc ? `: ${bindingTsType(sc, value, aliases)}` : null;
  };

  // Type each variant's ctor factories (return the variant type, params from the
  // ctor's field TypeExprs — ADR 0015) so `Circle(2)` is a `Shape`, not `any`.
  const body = codegen(prog, undefined, {
    runtime: false,
    annotate,
    annotateCtor: (s, c) => ctorFactoryTs(s.name, s.params, c),
    flattenPipe: true,
  });

  const parts = [typeHeader.join("\n"), runtimeLine, body].filter((p) => p !== "");
  return ok(`${parts.join("\n\n")}\n`);
};
