/**
 * TypeScript backend — AST → typed `.ts` source (see docs/compiler.md).
 * Not a fresh emitter: it orchestrates the two backends we already have. Types
 * come from `dts.ts` (the `.d.ts` writer's HM-type → TS-type machinery, reused
 * inline); values come from `codegen.ts` via its `annotate` and `annotateCtor`
 * hooks, which splice each binding's / ctor factory's type in.
 *
 * Runtime helpers (`_curry`, `add`, …) are imported from the typed runtime module
 * (`src/runtime.ts`, generated by scripts/gen-runtime.ts) instead of inlined — so
 * the emitted `.ts` is strict-`tsc`-clean end to end. The import specifier is
 * configurable (`runtimeImport`), defaulting to the published package name.
 */
import { isErr, ok, type Result } from "@onrails/result";
import type { Expr, Program } from "./ast";
import { codegen, collectRuntimeDeps } from "./codegen";
import { toTypedProgram } from "./compile";
import {
  aliasTsDecl,
  bindingTsType,
  builtinDeclsIn,
  ctorCallTs,
  ctorFactoryTs,
  emptyCollTs,
  genericLambdaParams,
  guardParamTs,
  lambdaParamTypesTs,
  referencedBuiltinTypeDecls,
  typeDecl,
  unionGenericNames,
} from "./dts";
import type { Diagnostic } from "./errors";
import type { Env, Scheme, TypeAt } from "./infer";
import { preludeNamespaces } from "./prelude";
import type { Span } from "./span";
import type { AliasDef } from "./types";

export type CodegenTsOptions = { runtimeImport?: string };

export const DEFAULT_RUNTIME_IMPORT = "@mochi/runtime";

/**
 * Visit the span of every lambda AND every empty-collection literal (`#{}`/`[]`/
 * `@{}`) in an expression subtree, root included (ADR 0042). Used to scope a
 * generic binding's letters over the annotatable nodes nested in its body: each
 * visited span is mapped to that binding's letter assignment, so an inner lambda
 * param or an empty seed can name those letters. The binding's own value-lambda
 * span is visited too, but `annotateParams` resolves it via `genericBindingLambda`
 * first, so the mapping is harmless.
 */
const forEachScopedSpan = (e: Expr, f: (span: Span) => void): void => {
  switch (e.kind) {
    case "lambda":
      f(e.span);
      forEachScopedSpan(e.body, f);
      return;
    case "call":
      forEachScopedSpan(e.fn, f);
      for (const a of e.args) forEachScopedSpan(a, f);
      return;
    case "letin":
    case "letbind":
      forEachScopedSpan(e.value, f);
      forEachScopedSpan(e.body, f);
      return;
    case "pipe":
      forEachScopedSpan(e.left, f);
      forEachScopedSpan(e.right, f);
      return;
    case "ternary":
      forEachScopedSpan(e.cond, f);
      forEachScopedSpan(e.then, f);
      forEachScopedSpan(e.else, f);
      return;
    case "match":
      forEachScopedSpan(e.scrutinee, f);
      for (const a of e.arms) {
        if (a.guard) forEachScopedSpan(a.guard, f);
        forEachScopedSpan(a.body, f);
      }
      return;
    case "record":
      for (const fld of e.fields) forEachScopedSpan(fld.value, f);
      if (e.spread) forEachScopedSpan(e.spread, f);
      return;
    case "field":
      forEachScopedSpan(e.target, f);
      return;
    case "tuple":
      for (const x of e.elements) forEachScopedSpan(x, f);
      return;
    case "arr":
    case "list":
    case "set":
      if (e.elements.length === 0) f(e.span); // empty `[]` / `@{}`
      for (const x of e.elements) forEachScopedSpan(x.expr, f);
      return;
    case "map":
      if (e.entries.length === 0) f(e.span); // empty `#{}`
      for (const en of e.entries) {
        forEachScopedSpan(en.key, f);
        forEachScopedSpan(en.value, f);
      }
      return;
    case "interp":
      for (const p of e.parts) if (typeof p !== "string") forEachScopedSpan(p, f);
      return;
    default:
      return; // num / bool / str / ref — no nested expressions
  }
};

/**
 * The inference result + cross-module wiring a module needs to emit its `.ts`.
 * A single file has empty `importLines`/`importedKeys`; a module in a graph
 * (build --emit=ts) supplies its dependency imports and destructure keys.
 */
export type TsEmitContext = {
  env: Env;
  aliases: AliasDef[];
  types: TypeAt[];
  letParams: TypeAt[];
  importedKeys: Map<string, string[]>;
  importLines: string[];
  runtimeImport: string;
};

/**
 * Emit one module's typed `.ts` from a prepared context. Type header (referenced
 * builtin unions + this module's own `type` decls as `export type`), then any
 * cross-module imports, then the runtime import, then the codegen body with
 * per-binding / per-ctor annotations and pipe flattening. Pure — inference and
 * import resolution happen in the caller (`codegenTs` for a file, the graph
 * driver for `build --emit=ts`).
 */
export const emitTsModule = (prog: Program, ctx: TsEmitContext): string => {
  const aliasByName = new Map(ctx.aliases.map((a) => [a.name, a]));
  const typeHeader = [
    ...referencedBuiltinTypeDecls(prog, (n) => ctx.env.get(n)),
    ...prog.stmts.flatMap((s) => {
      if (s.kind !== "type") return [];
      const a = aliasByName.get(s.name);
      return [a ? aliasTsDecl(a) : typeDecl(s.name, s.params, s.ctors)];
    }),
  ];

  const deps = collectRuntimeDeps(prog);

  // Per-node inferred types, keyed by span, for annotating lambda params below.
  const typeAt = new Map(ctx.types.map((t) => [`${t.span.start}:${t.span.end}`, t.type]));
  // Monomorphic types for polymorphic-but-single-use `let` bindings, keyed by
  // value span — annotates top-level `const`s and `let … in` IIFE params so tsc
  // types the empty collections inside their values (ADR 0035).
  const letParamAt = new Map(ctx.letParams.map((t) => [`${t.span.start}:${t.span.end}`, t.type]));

  // Annotate function-valued top-level lets. Lambda params are where TS inference
  // is weakest (bare `(x) => …` infers `any` under strict) and where the
  // generic/nominal signature pays off. A non-function polymorphic binding has no
  // place to bind generics — dts renders its escaped vars as `unknown` — so
  // annotating it would be worse than TS's own inference; skip it.
  const annotate = (name: string, value: Expr): string | null => {
    if (name.startsWith("$")) return null;
    // A polymorphic-but-monomorphically-used non-lambda binding (`let emptyReg =
    // { ctors: #{}, … }`): annotate `const name: T` with the resolved use type so
    // tsc types its empty collections, which its own inference erases (ADR 0035).
    if (value.kind !== "lambda") {
      const t = letParamAt.get(`${value.span.start}:${value.span.end}`);
      const ts = t ? emptyCollTs(t, ctx.aliases) : null;
      return ts ? `: ${ts}` : null;
    }
    const sc = ctx.env.get(name);
    return sc ? `: ${bindingTsType(sc, value, ctx.aliases)}` : null;
  };

  // The value lambda of each GENERIC top-level function binding, keyed by span →
  // its scheme (ADR 0032). Its params are annotated in full and the arrow carries
  // a generic head, so polymorphic inner params name the letters instead of being
  // erased to `any`/`unknown` by `_curry`.
  const genericBindingLambda = new Map<string, Scheme>();
  // Each annotatable node (lambda, empty-collection literal) NESTED in a generic
  // binding's value body → that binding's letter map (ADR 0042). The binding's
  // `<A, B>` head (ADR 0032) lexically scopes its whole body, so a nested param
  // or seed may name those letters. Scoped PER binding (not a global union):
  // letters are positional, so the same id could be `A` in one scheme and `C` in
  // another; a nested node must use exactly its own binding's assignment to match
  // the head it renders under.
  const scopedNames = new Map<string, Map<number, string>>();
  for (const s of prog.stmts) {
    if (s.kind !== "let" || s.value.kind !== "lambda" || s.name.startsWith("$")) continue;
    const sc = ctx.env.get(s.name);
    // Type vars OR row vars: a row-poly binding (`st => {...st}`, no type vars)
    // still needs the generic head so its open-row params emit `{…} & R` under
    // a scoped `<R>` (ADR 0034), not a closed record dropping the row var.
    if (sc && (sc.vars.length > 0 || sc.rvars.length > 0)) {
      genericBindingLambda.set(`${s.value.span.start}:${s.value.span.end}`, sc);
      const names = unionGenericNames([sc]); // this scheme's own id → letter map
      forEachScopedSpan(s.value, (sp) => scopedNames.set(`${sp.start}:${sp.end}`, names));
    }
  }

  // Annotate each lambda's params from its inferred curried type (ADR 0028) —
  // concrete types only, no generic head; generic params stay bare (typed
  // contextually by tsc). Exception (ADR 0032): a generic binding's value lambda
  // gets a generic head + ALL params annotated, so its polymorphic inner params
  // name the letters rather than falling to `any`/`unknown` through `_curry`.
  // Inner lambdas (ADR 0042): pass the enclosing binding's letters so a param
  // over them renders the letters instead of falling to `unknown` where tsc
  // cannot infer through a nested higher-order call (`map(f, filter(g, xs))`).
  const annotateParams = (span: Span, arity: number) => {
    const key = `${span.start}:${span.end}`;
    const sc = genericBindingLambda.get(key);
    const g = sc ? genericLambdaParams(sc, arity, ctx.aliases) : null;
    if (g) return g;
    const t = typeAt.get(key);
    const names = scopedNames.get(key);
    return { generics: "", params: t ? lambdaParamTypesTs(t, arity, ctx.aliases, names) : [] };
  };

  // The concrete type each guard-form arm narrows FROM (ADR 0031). codegen turns
  // it into a type-predicate guard so nested-pattern handlers narrow — ts-pattern
  // only refines handler input for `x is U` guards, not boolean ones.
  const guardBaseType = (scrutinee: Expr) => {
    const t = typeAt.get(`${scrutinee.span.start}:${scrutinee.span.end}`);
    return t ? guardParamTs(t, ctx.aliases) : null;
  };

  // An empty collection literal (`#{}`/`[]`) — annotate with its resolved
  // element types so the seed flows to a concretely-typed state field (ADR 0035).
  const annotateEmpty = (e: Expr) => {
    const key = `${e.span.start}:${e.span.end}`;
    const t = typeAt.get(key);
    // ADR 0042: an empty seed inside a generic binding may name that binding's
    // letters (`new Map<string, … & D>()`), where its element type is otherwise
    // free and would render `unknown`.
    return t ? emptyCollTs(t, ctx.aliases, scopedNames.get(key)) : null;
  };

  // A `let x = v in …` whose value is polymorphic but used at one monomorphic
  // type: annotate the IIFE param so tsc contextually types the value's empty
  // collections (ADR 0035). Keyed by value span (`infer.letParams`).
  const annotateLetin = (value: Expr) => {
    const t = letParamAt.get(`${value.span.start}:${value.span.end}`);
    return t ? emptyCollTs(t, ctx.aliases) : null;
  };

  // An applied parametric ctor call (`Ok("")`, `Err(e)`): cast it to its resolved
  // concrete type so the phantom param the argument doesn't pin can't widen to
  // `unknown` in a ts-pattern arm (ADR 0043). Per-node type table; `ctorCallTs`
  // renders only a fully-concrete `con`, so calls in a generic position stay bare.
  const annotateCall = (e: Expr) => {
    const t = typeAt.get(`${e.span.start}:${e.span.end}`);
    return t ? ctorCallTs(t, ctx.aliases) : null;
  };

  // Type each variant's ctor factories (return the variant type, params from the
  // ctor's field TypeExprs — ADR 0015) so `Circle(2)` is a `Shape`, not `any`.
  const body = codegen(prog, ctx.importedKeys, {
    runtime: false,
    annotate,
    annotateParams,
    guardBaseType,
    annotateEmpty,
    annotateLetin,
    annotateCall,
    annotateCtor: (s, c) => ctorFactoryTs(s.name, s.params, c),
    flattenPipe: true,
    tupleHelper: true, // emit `_tuple(a, b)` so tsc infers a tuple (ADR 0036)
    moduleExt: "", // `import … from "./mod"` — tsc resolves to the sibling `.ts`
  });

  // A guard predicate can name a builtin variant (`Option`) the header didn't
  // already emit — inject its decl now that the body text exists (ADR 0031).
  const header = [...builtinDeclsIn(body, typeHeader.join("\n")), ...typeHeader];

  // `_tuple` isn't reachable by `collectRuntimeDeps` (a tuple AST node carries no
  // runtime-name reference); it's a TS-emit device, so pull it in from the body
  // text once emitted (ADR 0036), like `builtinDeclsIn` above.
  const allDeps = body.includes("_tuple(") ? [...deps, "_tuple"] : deps;
  const runtimeLine = allDeps.length
    ? `import { ${allDeps.join(", ")} } from ${JSON.stringify(ctx.runtimeImport)};`
    : "";

  const parts = [header.join("\n"), ctx.importLines.join("\n"), runtimeLine, body].filter(
    (p) => p !== "",
  );
  return `${parts.join("\n\n")}\n`;
};

/**
 * Compile a single `.mochi` source to a typed `.ts` module (CLI `mochi ts`). Open
 * world, no cross-module imports resolved — a file that imports from another
 * module won't typecheck alone; use `build --emit=ts` for a graph.
 */
export const codegenTs = (
  src: string,
  opts: CodegenTsOptions = {},
): Result<string, Diagnostic[]> => {
  const r = toTypedProgram(src, { open: true, namespaces: preludeNamespaces });
  if (isErr(r)) return r;
  const { prog, res } = r.value;
  return ok(
    emitTsModule(prog, {
      env: res.env,
      aliases: res.aliases,
      types: res.types,
      letParams: res.letParams,
      importedKeys: new Map(),
      importLines: [],
      runtimeImport: opts.runtimeImport ?? DEFAULT_RUNTIME_IMPORT,
    }),
  );
};
